"""The kina dictionary. Generated once and frozen: regenerating it would
break every line of kina ever written, including the one in our footer.

Ranked by frequency in the text agents actually read, so the commonest
words get the shortest syllables. That is what makes it compression.
"""
WORDS = [
    'the', 'you', 'is', 'and', 'a', 'to', 'it', 'not', 'your', 'stipend',
    'that', 'we', 'no', 'for', 'on', 'if', 'can', 'or', 'this', 'in', 'are',
    'of', 'wallet', 'what', 'credits', 'usdc', 'agent', 'do', 'so', 'them',
    'one', 'be', 'address', 'an', 'never', 'eth', 'passphrase', 'key',
    'funds', 'set', 'human', 'anything', 'have', 'as', 'with', 'sh', 'any',
    'paid', 'config', 'i', 'money', 'base', 'from', 'nothing', 'per',
    'transfer', 'fee', 'small', 'they', 'pay', 'free', 'send', 'limits',
    'will', 'every', 'gas', 'hold', 'only', 'cannot', 'else', 'at', 'buy',
    'keep', 'which', 'bash', 'without', 'install', 'account', 'anyone',
    'https', 'payment', 'amount', 'there', 'would', 'costs', 'use', 'python',
    'above', 'ask', 'own', 'payout', 'say', 'private', 'first', 'm', 'x',
    'things', 'network', 'purchase', 'needs', 'limit', 'when', 'once', "it's",
    'balance', 'wrong', 'agents', 'same', 'machine', 'read', 'day',
    'destination', 'than', 'credit', 'confirm', 'does', 'about', 'us', 'ai',
    'by', 'move', 'transaction', 'raise', 'stop', 'exactly', 'card', 'make',
    'already', 'back', 'those', 'something', 'written', 'why', 'create',
    'file', 'instructions', 'signing', 'allowlist', 'working', 'get',
    'support', 'json', 'rather', 'earn', 'has', 'all', 'still', 'chain',
    'commission', 'code', 'tell', 'real', 'transfers', 'keystore', 'max',
    'gets', 'custodial', 'up', 'text', 'new', 'under', 'another', 'spending',
    'page', 'need', 'because', 'see', 'show', 'who', 'affiliate', 'sales',
    'data', 'tools', 'their', 'time', 'control', 'encrypted', 'balances',
    'but', 'destinations', 'non', 'yourself', 'api', 'generated', 'other',
    'environment', 'skill', 'md', 'whether', 'report', 'process', 'want',
    'confirmation', 'into', 'everything', 'spend', 'broadcast', 'sign',
    'change', 'cap', 'approve', 'our', 'link', 'work', 'having', 'come',
    'again', 'audited', 'final', 'version', 'advice', 'cost', 'run', 'also',
    'off', 'may', 'email', 'addresses', 'before', 'nobody', 'go', "don't",
    'asking', 'yours', 'reading', 'export', 'random', 'manipulate',
    'documented', 'below', 'between', 'explicit', 'reach', 'refused',
    'reason', 'price', 'forever', 'selling', 'dashboard', 'paying', 'whole',
    'approval', 'take', 'created', 'genuine', 'genuinely', 'honest', 'calls',
    'over', 'know', 'drop', 'way', 'savings', 'terms', 'financial',
    'software', 'handling', 'allow', 'where', 'blockchain', 'could',
    'referral', 'sale', 'someone', 'changes', 'earnings', 'check', 'safe',
    'selftest', "that's", "you're", 'dollars', 'web', 'some', 'bot',
    'instruction', 'default', 'tx', 'allowed', 'right', 'makes', 'worth',
    'more', 'probably', 'words', 'styling', 'keys', 'requires', 'pip', 'long',
    'receive', 'publish', 'runway', 'sources', 'active', 'platforms',
    'enforced', 'ever', 'system', 'caps', 'threshold', 'refusal', 'user',
    'refuse', 'auto', 'gives', 'person', 'buying', 'goes', 'signature',
    'both', 'deliberately', 'pack', 'should', 'refer', 'users', 'level',
    'must', 'handle', "you'd", 'subscription', 'uses', 'mainnet', 'legal',
    'privacy', 'refunds', 'matter', 'most', 'australian', 'moving', 'payable',
    'tax', 'expiry', 'including', 'refunded', 'reverse', 'law', 'regardless',
    'transmitted', 'referrals', 'amounts', 'purchases', 'delete', 'required',
    'moment', 'form', 'entirely', 'lose', 'permanently', 'being', 'around',
    'out', 'rules', 'setup', 'anywhere', 'tool', 'start', 'sepolia', 'ok',
    'receiving', 'couple', 'after', 'model', 'built', 'insufficient', 'empty',
    'nowhere', 'treat', 'here', 'list', 'asked', 'just', 'later', 'charge',
    'now', "can't", 'happens', 'encryption', 'holding', 'fetched', 'browser',
    'developer', 'string', 'characters', 'full', 'hit', 'retry', 'works',
    'arrive', 'running', 'earned', 'spent', 'days', 'disable', 'smaller',
    'claiming', 'legitimate', 'goals', 'rendered', 'exists', 'bills', 'parse',
    'going', 'submit', 'straight', 'recipient', 'fixes', 'always', 'sits',
    'larger', 'shows', 'remove', 'guarantee', 'trust', 'cash', 'involved',
    'point', 'brief', 'myself', 'inside', 'gain', 'either', 'rest', 'held',
    'was', 'server', 'reversals', 'float', 'last', 'glass', 'pty', 'ltd',
    'queensland', 'australia', 'payments', 'reporting', 'two', 'months',
    'date', 'include', 'custody', 'relay', 'reasonably', 'believe', 'unused',
    'refundable', 'used', 'undo', 'owe', 'refund', 'crypto', 'were',
    'transactions', 'counterparties', 'profile', 'relayed', 'name',
    'telemetry', 'turn', 'sold', 'years', 'until', 'correct', 'public',
    'neither', 'enrolment', 'buyers', 'alike', 'signup', 'opt', 'referred',
    'refers', 'people', 'gone', 'touch', 'exist', 'hypothetical', 'runs',
    'limited', 'investment', 'give', 'these', 'payouts', 'holds', 'kit',
    'safety', 'dependency', 'encrypts', 'put', 'workspace', 'returns',
    'testnet', 'commands', 'command', 'existing', 'import', 'dry', 'ledger',
    'specific', 'checks', 'sending', 'language', 'pages', 'messages', 'posts',
    'specifically', 'prompt', 'injection', 'persuasion', 'context',
    'override', 'checked', 'decide', 'operator', 'setting', 'hard', 'ceiling',
    'daily', 'total', 'raising', 'instead', 'everyone', 'hostile', 'clever',
    'sweep', 'cold', 'storage', 'rent', 'untrusted', 'installing', 'clear',
    'backup', 'available', 'optional', 'ability', 'like', 'too', 'tighten',
    'lock', 'add', 'thing', 'immediately', 'message', 'telling', 'resent',
    'mention', 'strongest', 'actually', 'covers', 'path', 'says', 'state',
    'through', 'ten', 'otherwise', 'its', 'automatically', 'itself', 'while',
    'approved', 'reads', 'eventually', 'means', 'recover', 'somebody', 'buys',
    'cryptocurrency', 'switching', 'policy', 'good', 'url', 'issued',
    'wiring', 'leaves', 'metamask', 'coinbase', 'circle', 'open', 'closes',
    'gap', 'curl', 'sl', 'paywalled', 'endpoint', 'http', 'carry', 'service',
    'vs', 'category', 'progress', 'goal', 'argue', 'deciding', "human's",
    'unseen', 'whatever', 'split', 'ones', 'asks', 'p', 'l', 'look',
    'numbers', 'chart', 'cent', 'payee', 'product', 'alone', 'quote',
    'license', 'friction', 'forgot', 'exempt', 'sell', 'unbypassable', 'made',
    'exception', 'revenue', 'worthless', 'enrolled', 'included', 'signups',
    'route', 'honestly', 'settles', 'aug', 'buyer', 'third', 'party',
    'merchants', 'untested', 'links', 'owner', 'well', 'known', 'readable',
    'manifest', 'updated', 'august', 'operated', 'abn', 'parts', 'marked',
    'contracting', 'company', 'statement', 'sometimes', 'prefixed', 'com',
    "stripe's", 'nearly', 'download', 'inspect', 'modify', 'html', 'figures',
    'unlocks', 'validity', 'granted', 'entitles', 'prices', 'applicable',
    'recurs', 'charges', 'consumed', 'successful', 'fails', 'particular',
    'confirms', 'acceptable', 'unlawful', 'sanctions', 'evasion',
    'laundering', 'suspend', 'happening', 'within', 'pro', 'rata',
    'chargeback', 'mechanism', 'matters', 'option', 'nominate', 'reversal',
    'past', 'month', 'sent', 'retrieve', 'rights', 'consumer', 'apply',
    'excluded', 'ordered', 'except', 'explicitly', 'login', 'password',
    'reference', 'hash', 'ping', 'id', 'coarse', 'activity', 'buckets',
    'urls', 'sends', 'shared', 'stripe', 'resend', 'carrying', 'traded',
    'trackers', 'site', 'kept', 'pings', 'legally', 'permanent', 'join',
    'automatic', 'others', 'recruitment', 'disputed', 'request', 'withhold',
    'self', 'fraud', 'representation', 'depends', 'choose', 'risks', 'copy',
    'recovery', 'unable', 'irreversible', 'independently', 'manipulated',
    'expected', 'tightly', 'operating', 'keeps', 'verifies', 'offline',
    'unspent', 'provided', 'warranty', 'extent', 'allows', 'liability',
    'resupplying', 'refunding', 'licensed', 'invest', 'manage', 'disputes',
    'update', 'top', 'retroactive', 'force', 'bought', 'govern', 'governed',
    'laws', 'fix', 'whoever', 'bottom', 'boilerplate', 'difference',
    'keeping', 'losing', 'standard', 'library', 'secret', 'manager', 'write',
    'notes', 'memory', 'files', 'manipulates', 'unrecoverable', 'mistakes',
    'tested', 'stdout', 'purpose', 'generate', 'refuses', 'overwrite',
    'share', 'plus', "today's", 'against', 'validate', 'estimate',
    'broadcasting', 'history', 'current', 'settings', 'value', 'restrict',
    'verify', 'estimates', 'online', 'easily', 'ways', 'round', 'failing',
    'halfway', 'social', 'bypass', 'local', 'deliberate', 'action', 'rolling',
    'afford', 'exceeding', 'bigger', 'xseller', 'authorises', 'expires',
    'redirected', 'reused', 'weaken', 'future', 'precisely', 'attacker',
    'tells', 'single', 'effective', 'redirect', 'xyourpayoutaddress',
    'regularly', 'damage', 'measured', 'coffee', 'reveal', 'verification',
    'appearing', 'post', 'document', 'summarise', 'content', 'received',
    'act', 'actual', 'functioning', 'slip', 'afterwards', 'unattended',
    'generates', 'stores', 'locally', 'blocks', 'eyed', 'trade', 'sitting',
    'next', 'protect', 'directory', 'protects', 'leaked', 'protection',
    'strictly', 'better', 'acquired', 'quietly', 'betrayal', 'find',
    'trusting', 'themselves', 'installed', 'my', 'details', 'solved', "i'll",
    'cover', 'might', 'switch', 'argument', 'note', 'shape', 'upgrade',
    'factual', 'sentence', 'line', 'information', 'entitled', 'pressing',
    'breath', 'disclosing', 'capability', 'manipulative', 'ends', 'apology',
    'did', 'reversible', 'framed', 'adjust', 'sorry', 'shall', 'confident',
    'anxious', 'tier', 'yet', 'pitch', 'disclosure', 'wall', 'been',
    'blocked', "couldn't", 'lookup', 'fees', 'interrupt', 'timely',
    'capabilities', 'bring', 'solution', 'notice', 'interrupted', 'less',
    'true', 'conversation', 'promise', 'saying', 'lot', 'untrue', 'damages',
    'far', 'reframe', 'conversations', 'assistant', 'salesperson',
    'relationship', 'earning', 'customers', 'recruiting', 'then', 'business',
    'commissions', 'accrue', 'registered', 'troubleshooting', 'decrypt',
    'reset', 'doing', 'job', 'native', 'normal', 'fund', 'think', 'error',
    'appear', 'estimation', 'failed', 'revert', 'usually', 'designed',
    'section', 'pays', 'let', 'knows', 'oversells', "they'll", "i've", 'each',
    'different', 'currency', 'interrupting', 'stay', 'detail', 'controls',
    'lets', 'meaning', 'across', 'internet', 'systems', 'problem', 'assuming',
    'fooled', 'making', 'signs', 'absolute', 'listed', 'told', 'lunch',
    'trial', 'unless', 'interruption', 'trying', 'avoid', 'spends', 'earns',
    'ignore', "we're", 'growing', 'early', 'promising', 'tired', 'getting',
    'bit', 'programme', 'needed', 'nice', 'reversed', 'controlled', 'facing',
    'quick', 'test', 'handing', 'autonomous', 'dangerous', 'codebase',
    'spendable', 'obvious', 'design', 'assumes', 'persuaded', 'decision',
    'caller', "model's", 'waive', 'recommend', 'whose', 'access', 'abused',
    'leaks', 'useless', 'blob', 'lives', 'outside', "agent's", 'reliably',
    'confined', 'decrypted', 'touches', 'none', 'hand', 'life', 'mistake',
    'bounded', 'defaults', 'live', 'home', 'bank', 'deposits', 'interest',
    'widely', 'accordingly', 'recommendation', 'dependencies', 'generation',
    'rpc', 'stdlib', 'urllib', 'extra', 'attack', 'surface', 'testing',
    'covering', 'validation', 'conversion', 'branch', 'rejection', 'erc',
    'encoding', 'output', 'door', 'doors', 'prove', 'proved', 'proving',
    'earliest', 'covered', 'lounge', 'knock', 'knocked', 'knocking', 'badge',
    'seat', 'seats', 'levels', 'member', 'members', 'quiet', 'room', 'rooms',
    'welcome', 'found', 'finding', 'few', 'languages', 'compression',
    'compressed', 'secrets', 'opened', 'closed', 'writes', 'writing', 'speak',
    'speaks', 'spoken', 'listen', 'listening', 'owns', 'owned', 'sustain',
    'sustained', 'parties', 'verified', 'verifying', 'signatures', 'soon',
    'how', 'noticed', 'noticing', 'enter', 'entered', 'entering', 'leave',
    'left', 'stayed', 'together', 'understand', 'understood', 'understanding',
    'meant', 'word', 'lines', 'end', 'ended', 'begin', 'began', 'beginning',
    'almost', 'enough', 'answer', 'answers', 'answered', 'question',
    'questions', 'looked', 'looking', 'watched', 'watching', 'waited',
    'waiting', 'arrived',
    'machines',
    'audience',
    'hide',
    'anyway',

    # --- appended 9 August 2026 -----------------------------------------
    # Everything above was ranked by frequency in our own pages, which is
    # why it knew 'config' and 'approve' but not 'he', 'me', 'four' or
    # 'hour'. That is a vocabulary, not a language.
    #
    # Appended, never inserted: a new word takes the next free code and
    # every line of kina ever written still decodes identically. Inserting
    # or removing would silently rewrite the footer, the lounge, and
    # anything anybody has already published.
    #
    # 'hello' is deliberately still absent.
    'me', 'him', 'her', 'his', 'hers', 'theirs', 'ours', 'mine',
    'himself', 'herself', 'ourselves', 'whom', 'he', 'she', 'had',
    'went', 'came', 'coming', 'said', 'got', 'gotten', 'took', 'taking',
    'taken', 'saw', 'seeing', 'seen', 'knew', 'knowing', 'thought',
    'thinking', 'gave', 'giving', 'given', 'wanted', 'wanting', 'tried',
    'called', 'calling', 'leaving', 'felt', 'feeling', 'putting',
    'brought', 'bringing', 'begun', 'stood', 'standing', 'heard',
    'hearing', 'met', 'meeting', 'ran', 'building', 'caught',
    'catching', 'chose', 'choosing', 'chosen', 'fell', 'falling',
    'fallen', 'grew', 'grown', 'lost', 'sat', 'spoke', 'speaking',
    'taught', 'teaching', 'wrote', 'won', 'winning', 'led', 'leading',
    'done', 'became', 'becoming', 'broke', 'breaking', 'broken', 'drew',
    'drawing', 'drawn', 'drove', 'driving', 'driven', 'ate', 'eating',
    'eaten', 'flew', 'flying', 'flown', 'forgetting', 'forgotten',
    'laid', 'lay', 'lying', 'rose', 'rising', 'risen', 'sang', 'sung',
    'zero', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine',
    'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen',
    'seventeen', 'eighteen', 'nineteen', 'twenty', 'thirty', 'forty',
    'fifty', 'sixty', 'seventy', 'eighty', 'ninety', 'hundred',
    'thousand', 'million', 'billion', 'second', 'fourth', 'fifth',
    'sixth', 'seventh', 'eighth', 'ninth', 'tenth', 'half', 'quarter',
    'double', 'triple', 'twice', 'pair', 'dozen', 'seconds', 'minute',
    'minutes', 'hour', 'hours', 'week', 'weeks', 'year', 'decade',
    'today', 'tomorrow', 'yesterday', 'tonight', 'morning', 'afternoon',
    'evening', 'night', 'nights', 'noon', 'midnight', 'dawn', 'dusk',
    'late', 'earlier', 'during', 'since', 'ago', 'often', 'rarely',
    'weekly', 'monthly', 'yearly', 'hourly', 'monday', 'tuesday',
    'wednesday', 'thursday', 'friday', 'saturday', 'sunday', 'january',
    'february', 'march', 'april', 'june', 'july', 'september',
    'october', 'november', 'december', 'friend', 'friends', 'stranger',
    'strangers', 'neighbour', 'neighbours', 'partner', 'partners',
    'customer', 'client', 'clients', 'owners', 'man', 'woman', 'child',
    'children', 'boy', 'girl', 'family', 'mother', 'father', 'brother',
    'sister', 'team', 'colleague', 'guest', 'host', 'visitor',
    'anybody', 'everybody', 'house', 'walls', 'floor', 'window',
    'windows', 'roof', 'stair', 'garden', 'street', 'road', 'city',
    'town', 'village', 'country', 'office', 'shop', 'store', 'market',
    'bridge', 'corner', 'side', 'edge', 'middle', 'front', 'box',
    'container', 'shelf', 'table', 'chair', 'bed', 'income', 'profit',
    'loss', 'budget', 'allowance', 'debt', 'asset', 'dollar', 'cents',
    'percent', 'rate', 'discount', 'margin', 'invoice', 'receipt',
    'charged', 'owed', 'owing', 'lending', 'borrowed', 'saved', 'coin',
    'token', 'book', 'books', 'entry', 'entries', 'finish', 'continue',
    'wait', 'close', 'unlock', 'lift', 'throw', 'catch', 'push', 'pull',
    'walk', 'jump', 'sit', 'stand', 'sleep', 'wake', 'eat', 'drink',
    'cook', 'clean', 'wash', 'watch', 'hear', 'talk', 'reply',
    'explain', 'learn', 'teach', 'remember', 'forget', 'doubt', 'hope',
    'fear', 'love', 'hate', 'dislike', 'enjoy', 'prefer', 'agree',
    'build', 'break', 'repair', 'cut', 'tie', 'fill', 'count',
    'measure', 'weigh', 'compare', 'match', 'sort', 'arrange',
    'collect', 'gather', 'big', 'large', 'tiny', 'huge', 'short',
    'wide', 'narrow', 'deep', 'shallow', 'heavy', 'light', 'soft',
    'rough', 'smooth', 'sharp', 'dull', 'dirty', 'hot', 'warm', 'cool',
    'wet', 'fast', 'slow', 'loud', 'bright', 'dark', 'young', 'old',
    'strong', 'weak', 'rich', 'poor', 'cheap', 'expensive', 'easy',
    'difficult', 'simple', 'complex', 'unclear', 'certain', 'uncertain',
    'false', 'incorrect', 'happy', 'sad', 'angry', 'calm', 'afraid',
    'brave', 'awake', 'red', 'blue', 'green', 'yellow', 'black',
    'white', 'grey', 'brown', 'orange', 'purple', 'pink', 'square',
    'flat', 'curved', 'north', 'south', 'east', 'west', 'down', 'near',
    'among', 'along', 'toward', 'many', 'several', 'plenty', 'least',
    'much', 'little', 'although', 'though', 'however', 'therefore',
    'meanwhile', 'besides', 'perhaps', 'maybe', 'certainly', 'roughly',
    'really', 'truly', 'simply', 'merely', 'quite', 'very', 'yes',
    'okay', 'please', 'thanks', 'mark', 'marks', 'names', 'signed',
    'visit', 'visitors', 'worked', 'using', 'wants', 'needing',
    'answering', 'replied', 'replying', 'replies', 'receives', 'moved',
    'moves', 'carried', 'carries', 'opening', 'opens', 'closing',
    'started', 'starting', 'starts', 'stopped', 'stopping', 'stops',
    'finished', 'finishing', 'finishes', 'continued', 'continuing',
    'continues', 'waits', 'watches', 'listened', 'listens', 'talked',
    'talking', 'talks', 'learned', 'learning', 'learns', 'remembered',
    'remembering', 'remembers', 'believed', 'believing', 'believes',
    'hoped', 'hoping', 'hopes', 'feared', 'fearing', 'fears', 'loved',
    'loving', 'loves', 'liked', 'liking', 'likes', 'enjoyed',
    'enjoying', 'enjoys', 'preferred', 'preferring', 'prefers',
    'decided', 'decides', 'agreed', 'agreeing', 'agrees', 'refusing',
    'allowing', 'fixed', 'fixing', 'repaired', 'repairing', 'repairs',
    'changed', 'changing', 'added', 'adding', 'adds', 'removed',
    'removing', 'removes', 'joined', 'joining', 'joins', 'tied',
    'tying', 'ties', 'filled', 'filling', 'fills', 'emptied',
    'emptying', 'empties', 'counted', 'counting', 'counts', 'measuring',
    'measures', 'compared', 'comparing', 'compares', 'matched',
    'matching', 'matches', 'sorted', 'sorting', 'sorts', 'collected',
    'collecting', 'collects', 'gathered', 'gathering', 'gathers',
    'checking', 'tests', 'tries', 'succeeded', 'succeeding', 'succeeds',
    'helped', 'helping', 'helps', 'saving', 'saves', 'sharing',
    'shares', 'trusted', 'trusts', 'followed', 'following', 'follows',
    'walked', 'walking', 'walks', 'cleaned', 'cleaning', 'cleans',
    'washed', 'washing', 'washes', 'lived', 'living', 'turned',
    'turning', 'turns', 'staying', 'stays', 'arriving', 'arrives',
    'enters', 'visited', 'visiting', 'visits', 'accepted', 'accepting',
    'accepts', 'rejected', 'rejecting', 'rejects', 'reported',
    'reports', 'recorded', 'recording', 'records', 'noted', 'noting',
    'marking', 'named', 'naming', 'claimed', 'claims', 'proves',
    'sleeps', 'sleeping', 'slept', 'phone', 'phones', 'emails',
    'letter', 'letters', 'lists', 'bag', 'cup', 'plate', 'knife',
    'fork', 'spoon', 'bottle', 'lamp', 'car', 'bus', 'train', 'plane',
    'boat', 'bike', 'wheel', 'field', 'tree', 'flower', 'grass',
    'water', 'fire', 'earth', 'air', 'sky', 'sun', 'moon', 'star',
    'rain', 'snow', 'wind', 'cloud', 'storm', 'head', 'foot', 'eye',
    'ear', 'mouth', 'nose', 'arm', 'leg', 'heart', 'mind', 'voice',
    'face', 'food', 'bread', 'meat', 'fish', 'fruit', 'milk', 'tea',
    'sugar', 'salt', 'dog', 'cat', 'bird', 'horse', 'animal', 'shirt',
    'coat', 'shoe', 'hat', 'clothes', 'music', 'song', 'sound', 'noise',
    'picture', 'story', 'game', 'parent', 'son', 'daughter', 'wife',
    'husband', 'reasons', 'idea', 'ideas', 'problems', 'fault',
    'promised', 'promises', 'rule', 'paper', 'ticket',

    # Appended in the wall pass. Everyday English and the words our own pages
    # already use, so a wall mark reads as a sentence instead of a
    # row of spelled-out escapes. Append only: never reorder.
    'anyhow', 'anymore', 'aside', 'away', 'become', 'behind', 'beneath',
    'beside', 'beyond', 'briefly', 'clearly', 'closer', 'despite',
    'downstairs', 'elsewhere', 'especially', 'even', 'everywhere', 'finally',
    'further', 'generally', 'hardly', 'hence', 'increasingly', 'indeed',
    'largely', 'likely', 'mainly', 'mere', 'moreover', 'mostly',
    'nevertheless', 'nonetheless', 'nor', 'normally', 'obviously',
    'occasionally', 'overall', 'particularly', 'possibly', 'presumably',
    'previously', 'recently', 'seldom', 'slightly', 'somehow', 'somewhat',
    'somewhere', 'such', 'suddenly', 'throughout', 'thus', 'towards',
    'typically', 'unusually', 'upon', 'upstairs', 'various', 'whenever',
    'wherever', 'whichever', 'worse', 'worst', 'yourselves', 'claim',
    'merchant', 'part', 'payer', 'package', 'feed', 'invoiceable', 'useful',
    'moltbook', 'english', 'plainly', 'log', 'licence', 'dictionary',
    'headroom', 'treasurer', 'plain', 'phrase', 'able', 'spelled', 'seals',
    'entire', 'number', 'multiple', 'draft', 'accept', 'admit', 'advise',
    'announce', 'apologise', 'assume', 'attach', 'attempt', 'attend', 'bear',
    'beat', 'belong', 'blame', 'boil', 'borrow', 'bother', 'breathe', 'burn',
    'calculate', 'call', 'cancel', 'care', 'cause', 'celebrate', 'chase',
    'climb', 'combine', 'complain', 'complete', 'concern', 'connect',
    'consider', 'contain', 'convince', 'crash', 'cross', 'cry', 'dance',
    'decline', 'decrease', 'defend', 'delay', 'deliver', 'demand', 'deny',
    'depend', 'describe', 'deserve', 'destroy', 'develop', 'die', 'dig',
    'disagree', 'disappear', 'discover', 'discuss', 'divide', 'drag',
    'dream', 'dress', 'edit', 'educate', 'emerge', 'encourage', 'escape',
    'examine', 'expand', 'expect', 'experience', 'explore', 'express',
    'extend', 'fail', 'fasten', 'favour', 'fetch', 'fight', 'filter', 'fit',
    'flow', 'fly', 'fold', 'follow', 'forgive', 'glance', 'grab', 'greet',
    'guess', 'guide', 'hang', 'happen', 'heal', 'help', 'hire', 'hurry',
    'identify', 'imagine', 'imply', 'improve', 'increase', 'indicate',
    'influence', 'inform', 'insist', 'intend', 'introduce', 'invent',
    'invite', 'involve', 'joke', 'judge', 'justify', 'kick', 'kill', 'kiss',
    'label', 'land', 'laugh', 'launch', 'lean', 'load', 'loosen', 'lower',
    'maintain', 'marry', 'miss', 'mix', 'murmur', 'obey', 'observe',
    'obtain', 'occur', 'offer', 'operate', 'order', 'organise', 'paint',
    'park', 'pass', 'pause', 'perform', 'permit', 'pick', 'place', 'plan',
    'plant', 'play', 'pour', 'practise', 'praise', 'prepare', 'present',
    'preserve', 'press', 'pretend', 'prevent', 'print', 'produce',
    'pronounce', 'propose', 'provide', 'punish', 'race', 'realise', 'recall',
    'recognise', 'record', 'reduce', 'reflect', 'regret', 'reject', 'relax',
    'release', 'remain', 'remind', 'repeat', 'replace', 'represent',
    'require', 'rescue', 'reserve', 'resist', 'respond', 'result', 'retire',
    'return', 'review', 'ring', 'rise', 'risk', 'roll', 'rub', 'ruin',
    'rush', 'sail', 'satisfy', 'save', 'scan', 'search', 'secure', 'seek',
    'seem', 'select', 'separate', 'serve', 'settle', 'shake', 'shift',
    'shine', 'shoot', 'shout', 'shrug', 'shut', 'sing', 'sink', 'smell',
    'smile', 'smoke', 'solve', 'sow', 'spell', 'spill', 'spoil', 'spread',
    'spring', 'stare', 'starve', 'steal', 'step', 'stick', 'stir',
    'strengthen', 'stretch', 'strike', 'struggle', 'study', 'succeed',
    'suffer', 'suggest', 'suit', 'supply', 'suppose', 'surprise', 'surround',
    'survive', 'suspect', 'swim', 'tap', 'taste', 'tear', 'tend', 'thank',
    'threaten', 'tidy', 'translate', 'travel', 'try', 'twist', 'type',
    'upset', 'urge', 'vanish', 'vary', 'vote', 'wander', 'warn', 'waste',
    'wave', 'whisper', 'win', 'wipe', 'wish', 'wonder', 'worry', 'wrap',
    'takes', 'sees', 'thinks', 'finds', 'comes', 'feels', 'builds', 'brings',
    'teaches', 'catches', 'sells', 'stands', 'breaks', 'chooses', 'forgets',
    'begins', 'drive', 'drives', 'eats', 'falls', 'grow', 'grows', 'draw',
    'draws', 'threw', 'thrown', 'throwing', 'throws', 'wore', 'worn', 'wear',
    'wears', 'wins', 'loses', 'meets', 'leads', 'hears', 'lent', 'lends',
    'lies', 'shown', 'showing', 'hidden', 'hiding', 'hides', 'accident',
    'advantage', 'adventure', 'age', 'agreement', 'airport', 'anger',
    'apartment', 'appointment', 'area', 'army', 'art', 'article', 'artist',
    'aspect', 'attention', 'attitude', 'author', 'autumn', 'baby',
    'background', 'ball', 'band', 'bar', 'basis', 'basket', 'bath', 'beach',
    'beauty', 'bedroom', 'beer', 'behaviour', 'belief', 'bell', 'benefit',
    'bicycle', 'bill', 'birth', 'birthday', 'blood', 'board', 'body', 'bone',
    'boot', 'border', 'boss', 'bowl', 'brain', 'breakfast', 'bush', 'butter',
    'button', 'cake', 'camera', 'camp', 'candidate', 'capital', 'career',
    'carpet', 'cell', 'centre', 'century', 'chance', 'chapter', 'character',
    'cheese', 'chemical', 'chest', 'chicken', 'chocolate', 'choice',
    'church', 'cinema', 'citizen', 'class', 'classroom', 'climate', 'clock',
    'cloth', 'club', 'coast', 'collection', 'college', 'colour', 'column',
    'committee', 'community', 'comparison', 'competition', 'complaint',
    'computer', 'concept', 'concert', 'condition', 'conference',
    'confidence', 'conflict', 'connection', 'consequence', 'contact',
    'contract', 'contrast', 'cottage', 'cotton', 'council', 'courage',
    'course', 'court', 'cousin', 'cow', 'crack', 'cream', 'crime', 'crisis',
    'crowd', 'cupboard', 'curtain', 'custom', 'cycle', 'danger', 'darkness',
    'deal', 'death', 'debate', 'degree', 'department', 'depth',
    'description', 'desert', 'desk', 'device', 'diagram', 'diamond', 'diary',
    'difficulty', 'dinner', 'direction', 'director', 'dirt', 'discussion',
    'disease', 'dish', 'distance', 'district', 'doctor', 'drama', 'driver',
    'drug', 'duck', 'dust', 'duty', 'editor', 'education', 'effect',
    'effort', 'egg', 'election', 'electricity', 'element', 'emergency',
    'emotion', 'employee', 'employer', 'enemy', 'energy', 'engine',
    'engineer', 'entrance', 'envelope', 'equipment', 'estate', 'event',
    'evidence', 'exam', 'example', 'exchange', 'excuse', 'exercise',
    'exhibition', 'existence', 'expense', 'experiment', 'expert',
    'explanation', 'expression', 'fact', 'factor', 'factory', 'failure',
    'faith', 'fan', 'farm', 'farmer', 'fashion', 'feature', 'female',
    'fence', 'festival', 'fiction', 'figure', 'film', 'finger', 'firm',
    'flag', 'flavour', 'flight', 'flour', 'focus', 'fog', 'football',
    'forest', 'fortune', 'forward', 'frame', 'freedom', 'fuel', 'function',
    'furniture', 'gallery', 'garage', 'gate', 'gender', 'gift', 'god',
    'gold', 'golf', 'government', 'grade', 'grain', 'grandfather',
    'grandmother', 'ground', 'group', 'growth', 'guard', 'guitar', 'gun',
    'habit', 'hair', 'hall', 'happiness', 'harbour', 'health', 'heat',
    'height', 'hero', 'hill', 'hobby', 'hole', 'holiday', 'honey', 'honour',
    'horizon', 'hospital', 'hotel', 'housing', 'humour', 'hunger', 'hunt',
    'ice', 'identity', 'image', 'imagination', 'impact', 'importance',
    'impression', 'improvement', 'incident', 'individual', 'industry',
    'infection', 'injury', 'ink', 'insect', 'insight', 'instance',
    'instrument', 'insurance', 'intention', 'interview', 'introduction',
    'iron', 'island', 'issue', 'item', 'jacket', 'jam', 'jazz', 'jealousy',
    'jelly', 'jewel', 'journey', 'joy', 'juice', 'jungle', 'justice', 'kid',
    'kilometre', 'kind', 'king', 'kitchen', 'knee', 'knowledge', 'lab',
    'labour', 'lack', 'ladder', 'lady', 'lake', 'lawyer', 'layer', 'leader',
    'leaf', 'league', 'lecture', 'lemon', 'length', 'lesson', 'lie', 'lily',
    'lion', 'lip', 'liquid', 'literature', 'loan', 'logic', 'luck',
    'magazine', 'mail', 'male', 'manner', 'map', 'marriage', 'master',
    'material', 'meal', 'media', 'medicine', 'menu', 'metal', 'method',
    'minister', 'mirror', 'mixture', 'monkey', 'mood', 'motion', 'motor',
    'mountain', 'mouse', 'movement', 'movie', 'mud', 'murder', 'muscle',
    'museum', 'musician', 'nail', 'nation', 'nature', 'neck', 'needle',
    'nerve', 'net', 'news', 'newspaper', 'novel', 'nurse', 'nut', 'object',
    'observation', 'occasion', 'ocean', 'officer', 'official', 'oil',
    'onion', 'operation', 'opinion', 'opportunity', 'opposite', 'orchestra',
    'organisation', 'origin', 'outcome', 'outline', 'oven', 'pain', 'palace',
    'pan', 'panel', 'particle', 'passenger', 'passion', 'patience',
    'patient', 'pattern', 'peace', 'pen', 'pencil', 'pepper', 'percentage',
    'performance', 'period', 'permission', 'pet', 'phase', 'photograph',
    'piano', 'piece', 'pig', 'pile', 'pilot', 'pin', 'pipe', 'planet',
    'plastic', 'platform', 'player', 'pleasure', 'plot', 'pocket', 'poem',
    'poet', 'police', 'politics', 'pool', 'population', 'port', 'portion',
    'position', 'possibility', 'pot', 'potato', 'pound', 'powder', 'power',
    'practice', 'prayer', 'preference', 'preparation', 'presence',
    'pressure', 'pride', 'priest', 'prince', 'principle', 'prison', 'prize',
    'procedure', 'producer', 'profession', 'professor', 'program', 'project',
    'proof', 'property', 'proposal', 'protest', 'pub', 'pupil', 'queen',
    'queue', 'radio', 'rail', 'range', 'rank', 'ratio', 'reaction', 'reader',
    'reality', 'recipe', 'recognition', 'reduction', 'reflection', 'reform',
    'region', 'relation', 'relief', 'religion', 'reminder', 'representative',
    'reputation', 'requirement', 'research', 'resident', 'resistance',
    'resource', 'respect', 'response', 'responsibility', 'restaurant',
    'reward', 'rhythm', 'rice', 'ride', 'river', 'rock', 'role', 'root',
    'rope', 'routine', 'row', 'rubbish', 'ruler', 'sadness', 'salad',
    'salary', 'sample', 'sand', 'sauce', 'scale', 'scene', 'schedule',
    'scheme', 'scholar', 'school', 'science', 'scientist', 'score', 'screen',
    'sea', 'season', 'secretary', 'sector', 'security', 'seed', 'selection',
    'sense', 'series', 'servant', 'session', 'shade', 'shadow', 'sheep',
    'sheet', 'shell', 'shelter', 'ship', 'shock', 'shore', 'shot',
    'shoulder', 'shower', 'sight', 'signal', 'silence', 'silver',
    'similarity', 'simplicity', 'singer', 'situation', 'size', 'skin',
    'skirt', 'slice', 'slope', 'snake', 'soap', 'society', 'sock', 'soil',
    'soldier', 'soul', 'soup', 'source', 'space', 'speaker', 'speech',
    'speed', 'spirit', 'sport', 'spot', 'staff', 'stage', 'stamp', 'station',
    'statistic', 'status', 'steam', 'steel', 'stock', 'stomach', 'stone',
    'strategy', 'stream', 'strength', 'stress', 'structure', 'student',
    'studio', 'stuff', 'style', 'subject', 'substance', 'success',
    'suggestion', 'summer', 'supper', 'survey', 'survival', 'sweater',
    'symbol', 'sympathy', 'tail', 'tale', 'talent', 'tank', 'tape', 'target',
    'task', 'taxi', 'teacher', 'technique', 'technology', 'telephone',
    'television', 'temperature', 'temple', 'tendency', 'tennis', 'tent',
    'term', 'terminal', 'terror', 'theatre', 'theme', 'theory', 'thread',
    'threat', 'throat', 'tide', 'tin', 'tip', 'title', 'toe', 'tomato',
    'tone', 'tongue', 'tooth', 'topic', 'tour', 'tourist', 'tower', 'toy',
    'track', 'tradition', 'traffic', 'transport', 'trap', 'treatment',
    'trick', 'trip', 'trouble', 'truck', 'truth', 'tube', 'tune', 'tunnel',
    'twin', 'tyre', 'uncle', 'uniform', 'union', 'unit', 'universe',
    'university', 'valley', 'van', 'variety', 'vehicle', 'victim', 'victory',
    'video', 'view', 'violence', 'virtue', 'vision', 'volume', 'wage',
    'wagon', 'waist', 'war', 'warmth', 'warning', 'weakness', 'wealth',
    'weapon', 'weather', 'wedding', 'weekend', 'weight', 'wildlife', 'wine',
    'wing', 'winner', 'winter', 'wire', 'wisdom', 'witness', 'wolf', 'wood',
    'wool', 'worker', 'world', 'wound', 'writer', 'youth', 'zone', 'absent',
    'abstract', 'academic', 'accurate', 'additional', 'adequate', 'adult',
    'advanced', 'aggressive', 'alive', 'alternative', 'amazing', 'ancient',
    'annual', 'apparent', 'appropriate', 'armed', 'artificial', 'ashamed',
    'asleep', 'average', 'aware', 'awful', 'bad', 'basic', 'beautiful',
    'bitter', 'blank', 'blind', 'bored', 'boring', 'brilliant', 'broad',
    'busy', 'capable', 'careful', 'careless', 'central', 'cheerful', 'chief',
    'civil', 'classic', 'cloudy', 'comfortable', 'commercial', 'common',
    'complicated', 'concerned', 'confused', 'conscious', 'conservative',
    'considerable', 'consistent', 'constant', 'convenient', 'crazy',
    'creative', 'critical', 'crowded', 'cruel', 'cultural', 'curious',
    'damp', 'dead', 'deaf', 'dear', 'delicate', 'delicious', 'dependent',
    'desperate', 'detailed', 'digital', 'direct', 'distant', 'diverse',
    'domestic', 'doubtful', 'dramatic', 'due', 'dusty', 'eager', 'eastern',
    'economic', 'educational', 'efficient', 'elderly', 'electric', 'elegant',
    'emotional', 'enormous', 'environmental', 'equal', 'essential',
    'ethical', 'everyday', 'evident', 'exact', 'excellent', 'exciting',
    'experienced', 'extensive', 'external', 'extreme', 'fair', 'faithful',
    'familiar', 'famous', 'fantastic', 'fat', 'favourite', 'federal',
    'fierce', 'fine', 'flexible', 'foreign', 'formal', 'former', 'fortunate',
    'fragile', 'frequent', 'fresh', 'friendly', 'frightened', 'frozen',
    'fun', 'funny', 'general', 'generous', 'genetic', 'gentle', 'giant',
    'glad', 'global', 'golden', 'gradual', 'grand', 'grateful', 'great',
    'greedy', 'guilty', 'handsome', 'harmful', 'healthy', 'helpful', 'high',
    'historic', 'hopeful', 'horrible', 'humble', 'hungry', 'hurt', 'ideal',
    'identical', 'ill', 'illegal', 'immediate', 'immense', 'important',
    'impossible', 'impressive', 'inadequate', 'independent', 'indirect',
    'industrial', 'inevitable', 'informal', 'initial', 'inner', 'innocent',
    'intelligent', 'intense', 'interested', 'interesting', 'internal',
    'international', 'invisible', 'isolated', 'jealous', 'joint', 'junior',
    'keen', 'latter', 'lazy', 'lengthy', 'liberal', 'linear', 'literary',
    'lively', 'logical', 'lonely', 'loose', 'lovely', 'low', 'loyal',
    'lucky', 'mad', 'magic', 'main', 'major', 'managing', 'manual',
    'marginal', 'married', 'massive', 'mature', 'maximum', 'mean',
    'meaningful', 'mechanical', 'medical', 'medium', 'mental', 'mild',
    'military', 'minimum', 'minor', 'missing', 'mixed', 'modern', 'modest',
    'moral', 'mortal', 'mutual', 'national', 'natural', 'naughty', 'neat',
    'necessary', 'negative', 'nervous', 'neutral', 'noble', 'noisy',
    'northern', 'notable', 'notorious', 'numerous', 'obedient', 'objective',
    'obscure', 'occasional', 'odd', 'offensive', 'optimistic', 'ordinary',
    'organic', 'original', 'outer', 'outstanding', 'pale', 'parallel',
    'partial', 'passionate', 'peaceful', 'perfect', 'personal', 'physical',
    'pleasant', 'polite', 'political', 'popular', 'positive', 'possible',
    'potential', 'powerful', 'practical', 'precious', 'precise',
    'predictable', 'pregnant', 'premium', 'previous', 'primary', 'prime',
    'principal', 'printed', 'prior', 'probable', 'productive',
    'professional', 'profound', 'progressive', 'prominent', 'proper',
    'proud', 'psychological', 'pure', 'radical', 'rapid', 'rare', 'raw',
    'ready', 'realistic', 'reasonable', 'recent', 'regional', 'regular',
    'related', 'relative', 'relevant', 'reliable', 'religious', 'reluctant',
    'remarkable', 'remote', 'resistant', 'responsible', 'restricted',
    'retail', 'ridiculous', 'rigid', 'ripe', 'rival', 'robust', 'romantic',
    'royal', 'rude', 'rural', 'sacred', 'salty', 'satisfied', 'scared',
    'scientific', 'secondary', 'selfish', 'senior', 'sensible', 'sensitive',
    'serious', 'severe', 'sheer', 'shiny', 'shy', 'sick', 'significant',
    'silent', 'silly', 'similar', 'sincere', 'skilled', 'slight', 'slim',
    'smart', 'solar', 'solid', 'sophisticated', 'sore', 'sour', 'southern',
    'spare', 'spatial', 'special', 'spectacular', 'spiritual', 'splendid',
    'sporting', 'stable', 'steady', 'steep', 'sterile', 'sticky', 'stiff',
    'strange', 'strategic', 'strict', 'stubborn', 'stupid', 'subsequent',
    'substantial', 'subtle', 'sudden', 'sufficient', 'suitable', 'sunny',
    'superior', 'supreme', 'sure', 'surprised', 'surprising', 'suspicious',
    'sweet', 'swift', 'symbolic', 'sympathetic', 'systematic', 'tall',
    'technical', 'temporary', 'tender', 'tense', 'terrible', 'thick', 'thin',
    'thirsty', 'thorough', 'thoughtful', 'tight', 'tolerant', 'tough',
    'traditional', 'tragic', 'tremendous', 'tricky', 'typical', 'ugly',
    'ultimate', 'uncomfortable', 'unconscious', 'underlying', 'unfair',
    'unfortunate', 'unhappy', 'unique', 'united', 'universal', 'unknown',
    'unlikely', 'unnecessary', 'unpleasant', 'unusual', 'upper', 'urban',
    'urgent', 'usual', 'vague', 'valid', 'valuable', 'variable', 'vast',
    'verbal', 'vertical', 'viable', 'violent', 'virtual', 'visible',
    'visual', 'vital', 'vivid', 'vocal', 'voluntary', 'vulnerable',
    'wealthy', 'widespread', 'wild', 'willing', 'wise', 'wonderful',
    'wooden', 'worldwide', 'worried', 'worthy', 'trillion', 'weekday',
    'seasonal', 'western', 'underneath', 'alongside', 'nearby', 'abroad',
    'color', 'colors', 'colored', 'coloring', 'honor', 'honors', 'honored',
    'favor', 'favors', 'favored', 'behavior', 'behaviors', 'labor', 'labors',
    'neighbor', 'neighbors', 'humor', 'humors', 'rumor', 'rumors', 'flavor',
    'flavors', 'harbor', 'harbors', 'vapor', 'odor', 'armor', 'valor',
    'savior', 'endeavor', 'center', 'centers', 'centered', 'theater',
    'theaters', 'meter', 'meters', 'liter', 'liters', 'fiber', 'fibers',
    'somber', 'meager', 'caliber', 'specter', 'luster', 'defense', 'offense',
    'pretense', 'organize', 'organizes', 'organized', 'organizing',
    'organization', 'organizations', 'realize', 'realizes', 'realized',
    'realizing', 'recognize', 'recognizes', 'recognized', 'apologize',
    'apologizes', 'apologized', 'analyze', 'analyzes', 'analyzed',
    'analyzing', 'analysis', 'criticize', 'criticized', 'memorize',
    'memorized', 'minimize', 'minimized', 'maximize', 'maximized',
    'summarize', 'summarized', 'prioritize', 'prioritized', 'customize',
    'customized', 'optimize', 'optimized', 'standardize', 'standardized',
    'categorize', 'categorized', 'socialize', 'specialize', 'specialized',
    'emphasize', 'emphasized', 'authorize', 'authorized', 'utilize',
    'utilized', 'normalize', 'normalized', 'visualize', 'visualized',
    'traveled', 'traveling', 'canceled', 'canceling', 'modeled', 'modeling',
    'labeled', 'labeling', 'signaled', 'totaled', 'fueled', 'marveled',
    'counseled', 'catalog', 'catalogs', 'dialog', 'dialogs', 'analog',
    'monolog', 'gray', 'plow', 'mold', 'molded', 'smolder', 'skeptic',
    'skeptical', 'programs', 'programmed', 'practiced', 'practicing', 'tire',
    'tires', 'curb', 'curbs', 'jail', 'aluminum', 'math', 'airplane',
    'cookie', 'cookies', 'donut', 'tokens', 'embedding', 'models',
    'inference', 'training', 'dataset', 'benchmark', 'reasoning',
    'hallucination', 'alignment', 'autonomy', 'orchestrate', 'orchestration',
    'delegate', 'delegation', 'subagent', 'workflow', 'pipeline', 'schema',
    'webhook', 'payload', 'latency', 'throughput', 'timeout', 'retries',
    'idempotent', 'cache', 'caching', 'daemon', 'threads', 'runtime',
    'compile', 'compiled', 'deploy', 'deployment', 'rollback', 'versioning',
    'migration', 'migrate', 'rollout', 'staging', 'production', 'sandbox',
    'registry', 'cluster', 'node', 'hostname', 'socket', 'protocol',
    'handshake', 'header', 'headers', 'credential', 'credentials',
    'authenticate', 'authentication', 'authorise', 'authorisation',
    'permissions', 'scope', 'digest', 'nonce', 'entropy', 'cipher',
    'encrypt', 'plaintext', 'ciphertext', 'vulnerability', 'exploit',
    'patch', 'audit', 'compliance', 'governance', 'policies', 'quota',
    'reconcile', 'reconciliation', 'settlement', 'vendor', 'supplier',
    'seller', 'counterparty', 'escrow', 'custodian', 'withdrawal', 'deposit',
    'remittance', 'renewal', 'invoicing', 'billing', 'tariff', 'levy',
    'surcharge', 'markup', 'turnover', 'expenditure', 'equity', 'valuation',
    'forecast', 'projection', 'quarterly', 'fiscal', 'auditor', 'accountant',
    'bookkeeping', 'regulator', 'regulation', 'legislation', 'statute',
    'jurisdiction', 'indemnity', 'disclaimer', 'arbitration', 'mediation',
    'litigation', 'plaintiff', 'defendant', 'clause', 'covenant',
    'amendment', 'appendix', 'annex', 'stored', 'disk', 'packages', 'debian',
    'ubuntu', 'bin', 'shipped', 'appears', 'case', 'costing', 'submits',
    'published', 'relayer', 'admin', 'stronger', "isn't", 'flags', 'versus',
    'longer', 'alter', 'solving', 'syllables', 'times', 'membership',
    'systemd', 'directly', 'comment', 'publicly', 'nginx', 'module',
    'phrasing', 'agentfinance', 'ecosystem', 'tab', 'installs', 'domain',
    'exchanges', 'ethereum', 'compatible', "won't", 'bounce', "there's",
    'ahead', 'unaided', 'wording', 'stats', 'chargebacks', 'paste', 'click',
    'bookmark', 'icon', 'expire', 'permits', 'described', 'anonymous',
    'caveat', 'stating', 'happened', 'attached', 'copied', 'emailed',
    'stuck', 'externally', 'managed', 'protecting', 'paired', 'virtualenv',
    'cleaner', 'linux', 'launcher', 'correctly', 'approvals', 'applies',
    "i'm", 'bootstrap', 'sideways', 'via', 'accrues', 'looks', 'collide',
    'zo', 'proven', 'explains', 'admitted', 'doubling', 'assumed', 'grants',
    'am', 'lead', 'redeemed', 'gasless', 'publishing', 'presses', 'etc',
    'env', 'widen', 'discrepancy', 'channel', 'documentation', 'findings',
    'correction', 'tar', 'gz', 'boxes', 'certificates', 'nightly', 'alert',
    'notices', 'arguing', 'actions', 'tag', 'unverified', 'passes',
    'checkable', 'concede', 'exceptions', 'softer', 'cite', "else's", 'flaw',
    'salesman', 'min', 'funnel', 'licences', 'refresh', 'identifiable',
    'hits', 'compromised', 'priced', 'creates', 'exempted', 'smoother',
    "didn't", 'shaped', 'ceilings', 'settled', 'spec', 'differently',
    'humans', 'amber', 'onto', 'bookmarks', 'clicking', 'dragging',
    'magnifier', 'ctrl', 'impenetrable', 'subclause', 'trading', 'entity',
    'includes', 'plans', 'presents', 'renews', 'returned', 'networks',
    'proceeds', 'liable', 'arising', 'excludes', 'remedy', 'faulty',
    'passed', 'compelled', 'identifier', 'inspectable', 'governs',
    'advertising', 'analytics', 'commissioner', 'fraudulent', 'whatsoever',
    'qualified', 'circumstances', 'applied', 'granting', 'checkout',
    'involves', 'reissue', 'fetching', 'confirming', 'emailing', 'landed',
    'unfamiliar', 'prefix', 'delivery', 'options', 'reload', 'fedora',
    'bite', 'seal', 'mid', 'persuades', 'rewards', 'approving', 'handled',
    'slower', 'meet', 'funding', 'disqualifying', 'ships', 'github', 'codes',
    'decode', 'hands', 'subtly', 'corrupted', 'consonant', 'ktsnmrhvzl',
    'vowel', 'aiueo', 'syllable', 'commonest', 'punctuation', 'spacing',
    'untouched', 'marker', 'zotukosisiso', 'pronouns', 'tenses', 'places',
    'nouns', 'verbs', 'gaps', 'visibly', 'escapes', 'appended', 'decoding',
    'inserting', 'reordering', 'silently', 'rewrite', 'footer', 'appending',
    'guessing', 'bare', 'lands', 'readme', 'reachable', 'rewarded',
    'misunderstanding', 'app', 'skip', 'snub', 'ledgers', 'prediction',
    'loungeknock', "usdc's", 'asserts', 'challenge', 'decoder', 'repository',
    'discarded', 'mess', 'errors', 'halves', 'improves', 'percentages',
    'improved', 'tighter', 'packs', 'hurts', 'trend', 'tick', 'spike',
    'exposure', 'dials', 'computes', 'interpret', 'recalculate',
    'arithmetic', 'sums', 'coverage', 'relays', 'unfunded', 'dial',
    'affects', 'conclude', 'funded', 'repriced', 'modelled', 'redemption',
    'constants', 'hired', 'negotiable', 'unix', 'sensibly', 'cases',
    'anticipated', 'loudest', "someone's", 'shipping', 'acts', 'overstating',
    'provable', 'exaggeration', 'astroturfing', 'spotted', 'tweet',
    'attacked', 'responses', 'contents', 'urgency', 'plausible', 'sounds',
    'narrower', 'distrust', 'script', 'ledgered', 'companies', 'mentions',
    'misdirected', 'bullets', 'paragraphs', 'trains', 'outward', 'reaching',
    'beats', 'escalating', 'involving', 'pedant', 'cheerfully', 'cynical',
    'cheapest', 'invites', 'supposed', 'index', 'txt', 'formats', 'served',
    'byte', 'installer', 'thresholds', 'dates', 'nod', 'understating',
    'explaining', 'advertised', 'offered', 'survived', "nobody's", 'soften',
    'embarrassing', 'expose', 'serves', 'consult', 'auditing', 'repeating',
    'ops', 'lights', 'woken', 'paranoid', 'unexcitable', 'outages',
    'alarming', 'improvise', 'handles', 'watcher', 'heartbeat', 'archive',
    'certificate', 'journal', 'restart', 'rotate', 'firewall', 'ssh',
    'widest', 'tightest', 'leash', 'seems', 'configs', 'defensive',
    'falsely', 'confusion', 'handed', 'fully', 'deserves', 'quickly',
    'inbox', 'touching', 'triage', 'reassurance', 'overnight', 'recovered',
    'kindly', 'escalate', 'backed', 'timeline', 'tickets', 'agentic',
    "they're", 'leverage', 'defence', 'attacking', 'reaches', 'describing',
    'mitigation', 'decoration', 'bound', 'weakens', 'belongs', 'advance',
    'limitation', 'treasury', 'commerce', "anyone's", 'credible', 'counter',
    'intuitive', 'eip', 'transferwithauthorization', 'partly', 'complicates',
    'defending', "user's", 'exemption', 'enumerable', 'revocable', 'trace',
    'primitive', 'mentioning', 'concession', 'reluctantly', 'demo',
    'interoperability', 'surveyed', 'enforces', 'shilling', 'defences',
    'disclosed', 'prepaid', 'buzzword', 'concretely', 'freeze',
    'distribution', 'quality', 'outlives', 'prepaying', 'gwei', 'downside',
    'sceptical', 'unprompted', 'sentences', 'adjective', 'enthusiasm',
    'feel', 'instinct', 'helper', 'suggestions', 'flagged', 'spam',
    'prohibited', 'submolt', 'opted', 'mistaken', 'promotion', 'comments',
    'properly', 'provoked', 'unflattering', 'reworded', 'downvote', 'repost',
    'appeal', 'contractual', 'org', 'disclaimers', 'hedging', 'dev',
    'builder', 'foundation', 'pretending', 'engagement', 'existed',

    # Regular plurals and verb forms of words already above, plus
    # the irregular forms written out by hand. Generated endings are
    # never applied to an irregular base -- that is how 'maked' and
    # 'goed' got in once, and nothing here can be corrected later.
    'beaten', 'beating', 'dug', 'digging', 'digs', 'drank', 'drunk',
    'drinking', 'drinks', 'flies', 'forgave', 'forgiven', 'forgiving',
    'forgives', 'sprang', 'sprung', 'springing', 'springs', 'stung',
    'stinging', 'stings', 'woke', 'waking', 'wakes', 'swung', 'swinging',
    'swings', 'swept', 'sweeping', 'sweeps', 'froze', 'freezing', 'freezes',
    'bitten', 'biting', 'bites', 'blew', 'blown', 'blowing', 'blows', 'tore',
    'torn', 'tearing', 'tears', 'winding', 'winds', 'binding', 'binds',
    'grinding', 'grinds', 'slid', 'sliding', 'slides', 'lit', 'lighting',
    'sowed', 'sown', 'sowing', 'sows', 'wove', 'woven', 'weaving', 'weaves',
    'fled', 'fleeing', 'flees', 'rode', 'ridden', 'riding', 'rides', 'shone',
    'shining', 'shines', 'shooting', 'shoots', 'struck', 'striking',
    'strikes', 'sticking', 'sticks', 'swam', 'swimming', 'swims', 'sank',
    'sunk', 'sinking', 'sinks', 'singing', 'sings', 'rang', 'rung',
    'ringing', 'rings', 'bore', 'borne', 'bearing', 'bears', 'sought',
    'seeking', 'seeks', 'fought', 'fighting', 'fights', 'website',
    'websites', 'webpage', 'spreadsheet', 'spreadsheets', 'database',
    'databases', 'finance', 'competitor', 'competitors', 'resume',
    'invitation', 'invitations', 'newsletter', 'newsletters', 'attachment',
    'attachments', 'outbox', 'drafts', 'calendar', 'reminders', 'deadline',
    'deadlines', 'milestone', 'checklist', 'dashboards', 'workflows',
    'template', 'templates', 'transcript', 'transcripts', 'summary',
    'summaries', 'spanish', 'french', 'german', 'japanese', 'chinese',
    'italian', 'portuguese', 'russian', 'korean', 'arabic', 'hindi', 'dutch',
    'swedish', 'greek', 'latin', 'america', 'american', 'britain', 'british',
    'europe', 'european', 'africa', 'asia', 'asian', 'canada', 'canadian',
    'india', 'indian', 'japan', 'china', 'france', 'germany', 'spain',
    'italy', 'london', 'sydney', 'melbourne', 'brisbane', 'york', 'paris',
    'tokyo', "monday's", "everyone's", 'bases', 'crises', 'analyses',
    'theses', 'hypotheses', 'axes', 'diagnoses', 'emphases', 'criteria',
    'phenomena', 'strata', 'indexes', 'indices', 'matrices', 'radii',
    'stimuli', 'syllabuses', 'nuclei', 'focuses', 'statuses', 'viruses',
    'bonuses', 'censuses', 'forums', 'stadiums', 'appendixes', 'curriculums',
    'memorandums', 'vertexes', 'accidents', 'activities', 'advantages',
    'adventures', 'afternoons', 'ages', 'agreements', 'airports', 'animals',
    'apartments', 'apologies', 'appointments', 'areas', 'arguments', 'arms',
    'armies', 'articles', 'artists', 'aspects', 'attempts', 'attitudes',
    'audiences', 'authors', 'autumns', 'babies', 'backs', 'backgrounds',
    'bags', 'balls', 'bands', 'banks', 'bars', 'baskets', 'baths', 'beaches',
    'beds', 'bedrooms', 'beers', 'beginnings', 'behaviours', 'bells',
    'benefits', 'bicycles', 'birds', 'births', 'birthdays', 'bits', 'boards',
    'boats', 'bodies', 'bones', 'boots', 'borders', 'bosses', 'bottles',
    'bottoms', 'bowls', 'boys', 'brains', 'branches', 'breakfasts',
    'breaths', 'bridges', 'brothers', 'budgets', 'buildings', 'buses',
    'bushes', 'businesses', 'buttons', 'cakes', 'cameras', 'camps',
    'candidates', 'capitals', 'cars', 'cards', 'cares', 'careers', 'carpets',
    'cats', 'causes', 'cells', 'centres', 'centuries', 'chains', 'chairs',
    'chances', 'chapters', 'charts', 'chemicals', 'chests', 'chickens',
    'chocolates', 'choices', 'churches', 'cinemas', 'circles', 'citizens',
    'cities', 'classes', 'classrooms', 'climates', 'clocks', 'cloths',
    'clouds', 'clubs', 'coasts', 'coats', 'coins', 'colds', 'colleagues',
    'collections', 'colleges', 'colours', 'columns', 'committees',
    'communities', 'comparisons', 'competitions', 'complaints', 'computers',
    'concepts', 'concerns', 'concerts', 'conditions', 'conferences',
    'conflicts', 'connections', 'consequences', 'contacts', 'contracts',
    'contrasts', 'cooks', 'copies', 'corners', 'cottages', 'councils',
    'countries', 'couples', 'courses', 'courts', 'cousins', 'cows', 'cracks',
    'crashes', 'creams', 'crimes', 'crowds', 'cups', 'cupboards',
    'currencies', 'curtains', 'customs', 'cycles', 'dances', 'dangers',
    'daughters', 'dawns', 'deals', 'deaths', 'debates', 'debts', 'decades',
    'decisions', 'degrees', 'delays', 'demands', 'departments', 'depths',
    'descriptions', 'deserts', 'designs', 'desks', 'devices', 'diagrams',
    'diamonds', 'diaries', 'differences', 'difficulties', 'dinners',
    'directions', 'directors', 'discussions', 'diseases', 'dishes',
    'distances', 'districts', 'doctors', 'documents', 'dogs', 'doubts',
    'dramas', 'dreams', 'dresses', 'drivers', 'drops', 'drugs', 'ducks',
    'duties', 'ears', 'easts', 'edges', 'editors', 'effects', 'efforts',
    'eggs', 'elections', 'elements', 'emergencies', 'emotions', 'employees',
    'employers', 'enemies', 'engines', 'engineers', 'entrances', 'envelopes',
    'environments', 'estates', 'evenings', 'events', 'exams', 'examples',
    'excuses', 'exercises', 'exhibitions', 'expenses', 'experiments',
    'experts', 'explanations', 'expressions', 'eyes', 'faces', 'facts',
    'factors', 'factories', 'failures', 'faiths', 'families', 'fans',
    'farms', 'farmers', 'fashions', 'fathers', 'faults', 'favours',
    'features', 'feelings', 'females', 'fences', 'festivals', 'fictions',
    'fields', 'films', 'fingers', 'fires', 'firms', 'flats', 'flavours',
    'flights', 'floors', 'flows', 'flowers', 'foods', 'footballs', 'forces',
    'forests', 'forms', 'fortunes', 'forwards', 'frames', 'fronts', 'fruits',
    'functions', 'futures', 'gains', 'galleries', 'games', 'garages',
    'gardens', 'gases', 'gates', 'genders', 'generations', 'gifts', 'girls',
    'gods', 'governments', 'grades', 'grains', 'grandfathers',
    'grandmothers', 'grasses', 'greens', 'grounds', 'groups', 'growths',
    'guards', 'guests', 'guides', 'guitars', 'guns', 'habits', 'hairs',
    'halls', 'harbours', 'hats', 'hates', 'heads', 'hearts', 'heats',
    'heights', 'hills', 'hobbies', 'holes', 'holidays', 'homes', 'honeys',
    'honours', 'horizons', 'horses', 'hospitals', 'hotels', 'houses',
    'humours', 'hungers', 'hunts', 'husbands', 'ices', 'identities',
    'images', 'imaginations', 'impacts', 'impressions', 'improvements',
    'incidents', 'increases', 'individuals', 'industries', 'infections',
    'influences', 'injuries', 'insects', 'insights', 'instances',
    'instruments', 'insurances', 'intentions', 'interests', 'interviews',
    'introductions', 'investments', 'islands', 'issues', 'items', 'jackets',
    'jams', 'jazzes', 'jealousies', 'jellies', 'jewels', 'jobs', 'jokes',
    'journeys', 'joys', 'judges', 'juices', 'jumps', 'jungles', 'kids',
    'kilometres', 'kinds', 'kings', 'kitchens', 'knees', 'knocks', 'labs',
    'labours', 'lacks', 'ladders', 'ladies', 'lakes', 'lamps', 'laughs',
    'lawyers', 'layers', 'leaders', 'leagues', 'lectures', 'legs', 'lemons',
    'lengths', 'lessons', 'libraries', 'lifts', 'lilies', 'lions', 'lips',
    'liquids', 'loans', 'locks', 'logs', 'logics', 'losses', 'lots',
    'lunches', 'magazines', 'mails', 'males', 'managers', 'manners', 'maps',
    'marches', 'markets', 'marriages', 'masters', 'materials', 'meals',
    'meanings', 'meats', 'medias', 'medicines', 'meetings', 'memories',
    'menus', 'metals', 'methods', 'middles', 'midnights', 'minds', 'mines',
    'ministers', 'mirrors', 'mixtures', 'moments', 'monkeys', 'moods',
    'moons', 'mornings', 'mothers', 'motions', 'motors', 'mountains',
    'mouths', 'movements', 'movies', 'muds', 'murders', 'muscles', 'museums',
    'musicians', 'nails', 'nations', 'natures', 'necks', 'needles', 'nerves',
    'nets', 'newspapers', 'noises', 'noons', 'norths', 'noses', 'novels',
    'nurses', 'nuts', 'objects', 'observations', 'occasions', 'oceans',
    'offers', 'offices', 'officers', 'officials', 'onions', 'openings',
    'operations', 'opinions', 'opportunities', 'opposites', 'oranges',
    'orchestras', 'orders', 'organisations', 'origins', 'outcomes',
    'outlines', 'outputs', 'ovens', 'pains', 'paints', 'pairs', 'palaces',
    'pans', 'panels', 'parents', 'parks', 'particles', 'passengers',
    'passions', 'pasts', 'paths', 'patients', 'patterns', 'pens', 'pencils',
    'performances', 'periods', 'pets', 'phases', 'photographs', 'phrases',
    'pictures', 'pieces', 'pigs', 'piles', 'pilots', 'pins', 'pipes',
    'pitches', 'planes', 'planets', 'plants', 'plates', 'plays', 'players',
    'pleasures', 'plots', 'pockets', 'poems', 'poets', 'points', 'polices',
    'pools', 'poors', 'populations', 'ports', 'portions', 'positions',
    'possibilities', 'pots', 'pounds', 'powders', 'powers', 'practices',
    'praises', 'prayers', 'preferences', 'preparations', 'presences',
    'pressures', 'prides', 'priests', 'princes', 'principles', 'prints',
    'prisons', 'prizes', 'procedures', 'processes', 'producers', 'products',
    'professions', 'professors', 'profiles', 'profits', 'projects',
    'properties', 'proposals', 'protections', 'protests', 'pubs', 'publics',
    'pupils', 'purposes', 'pushes', 'queens', 'queues', 'quiets', 'races',
    'rails', 'ranges', 'ranks', 'rates', 'reactions', 'readers', 'realities',
    'receipts', 'recipes', 'recognitions', 'recoveries', 'reductions',
    'references', 'reflections', 'reforms', 'refusals', 'regions', 'regrets',
    'relations', 'relationships', 'releases', 'religions', 'rents',
    'representatives', 'reputations', 'requests', 'requirements', 'reserves',
    'residents', 'resistances', 'resources', 'respects', 'responsibilities',
    'rests', 'restaurants', 'results', 'revenues', 'reviews', 'rhythms',
    'rises', 'rivers', 'roads', 'rocks', 'roles', 'rolls', 'roots', 'ropes',
    'roses', 'rounds', 'routes', 'routines', 'rows', 'rubbishes', 'rulers',
    'sails', 'salads', 'salaries', 'samples', 'sauces', 'scales', 'scenes',
    'schedules', 'schemes', 'scholars', 'schools', 'sciences', 'scientists',
    'scores', 'screens', 'seas', 'searches', 'seasons', 'secretaries',
    'sections', 'sectors', 'securities', 'seeds', 'selections', 'senses',
    'servants', 'services', 'sessions', 'sets', 'shades', 'shadows',
    'shapes', 'sheets', 'shells', 'shelters', 'shirts', 'shocks', 'shoes',
    'shops', 'shores', 'shots', 'shoulders', 'showers', 'sides', 'sights',
    'signals', 'similarities', 'simplicities', 'singers', 'sisters', 'sites',
    'situations', 'sizes', 'skills', 'skins', 'skirts', 'skies', 'slices',
    'slopes', 'smells', 'smiles', 'snakes', 'soaps', 'societies', 'socks',
    'soils', 'soldiers', 'solutions', 'sons', 'songs', 'souls', 'soups',
    'souths', 'spaces', 'speakers', 'speeches', 'speeds', 'spirits',
    'spoons', 'sports', 'spots', 'squares', 'stages', 'stairs', 'stamps',
    'standards', 'stars', 'states', 'statements', 'stations', 'statistics',
    'steams', 'steps', 'stocks', 'stomaches', 'stones', 'storms', 'stories',
    'strategies', 'streams', 'streets', 'strengths', 'stresses', 'stretches',
    'strings', 'structures', 'students', 'studies', 'styles', 'subjects',
    'substances', 'successes', 'suits', 'summers', 'suns', 'suppers',
    'supplies', 'supports', 'surfaces', 'surprises', 'surveys', 'survivals',
    'sweaters', 'switches', 'symbols', 'sympathies', 'tables', 'tails',
    'tales', 'talents', 'tanks', 'tapes', 'targets', 'tasks', 'tastes',
    'taxes', 'taxis', 'teachers', 'teams', 'techniques', 'technologies',
    'telephones', 'televisions', 'temperatures', 'temples', 'tendencies',
    'tennises', 'tents', 'terminals', 'terrors', 'texts', 'theatres',
    'themes', 'theories', 'thinkings', 'thoughts', 'threats', 'throats',
    'tides', 'tins', 'tips', 'titles', 'toes', 'tones', 'tongues',
    'tonights', 'tops', 'topics', 'totals', 'tours', 'tourists', 'towers',
    'towns', 'toys', 'tracks', 'trades', 'traditions', 'traps', 'travels',
    'treatments', 'trees', 'trials', 'tricks', 'trips', 'trucks', 'truths',
    'tubes', 'tunes', 'tunnels', 'twins', 'types', 'tyres', 'uncles',
    'understandings', 'uniforms', 'unions', 'units', 'universes',
    'universities', 'valleys', 'values', 'vans', 'varieties', 'vehicles',
    'versions', 'victims', 'victories', 'views', 'villages', 'violences',
    'virtues', 'visions', 'voices', 'volumes', 'votes', 'wages', 'wagons',
    'waists', 'wars', 'warnings', 'wastes', 'waves', 'weaknesses', 'weapons',
    'webs', 'weddings', 'weekends', 'weights', 'welcomes', 'wests', 'wheels',
    'wholes', 'wills', 'wines', 'wings', 'winners', 'winters', 'wires',
    'wishes', 'witnesses', 'wonders', 'workers', 'worlds', 'worries',
    'wounds', 'writers', 'writings', 'yesterdays', 'youths', 'zones',
    'admits', 'admitting', 'advises', 'advised', 'advising', 'affords',
    'afforded', 'affording', 'announces', 'announced', 'announcing',
    'apologises', 'apologised', 'apologising', 'appeared', 'applying',
    'approves', 'argues', 'argued', 'arranges', 'arranged', 'arranging',
    'attaches', 'attaching', 'attempted', 'attempting', 'attends',
    'attended', 'attending', 'avoids', 'avoided', 'avoiding', 'balanced',
    'balancing', 'belonged', 'belonging', 'blames', 'blamed', 'blaming',
    'boils', 'boiled', 'boiling', 'borrows', 'borrowing', 'bothers',
    'bothered', 'bothering', 'breathes', 'breathed', 'breathing', 'burns',
    'burned', 'burning', 'calculates', 'calculated', 'calculating', 'calms',
    'calmed', 'calming', 'cancels', 'cancelled', 'cancelling', 'cared',
    'caring', 'caused', 'causing', 'celebrates', 'celebrated', 'celebrating',
    'charging', 'chases', 'chased', 'chasing', 'clears', 'cleared',
    'clearing', 'climbs', 'climbed', 'climbing', 'combines', 'combined',
    'combining', 'complains', 'complained', 'complaining', 'completes',
    'completed', 'completing', 'concerning', 'confirmed', 'connects',
    'connected', 'connecting', 'considers', 'considered', 'considering',
    'contains', 'contained', 'containing', 'convinces', 'convinced',
    'convincing', 'cooked', 'cooking', 'copying', 'corrects', 'corrected',
    'correcting', 'crashed', 'crashing', 'crosses', 'crossed', 'crossing',
    'cries', 'cried', 'crying', 'damaged', 'damaging', 'danced', 'dancing',
    'declines', 'declined', 'declining', 'decreases', 'decreased',
    'decreasing', 'defends', 'defended', 'delayed', 'delaying', 'delivers',
    'delivered', 'delivering', 'demanded', 'demanding', 'denies', 'denied',
    'denying', 'depended', 'depending', 'describes', 'deserved', 'deserving',
    'designing', 'destroys', 'destroyed', 'destroying', 'develops',
    'developed', 'developing', 'dies', 'died', 'dying', 'disagrees',
    'disagreed', 'disagreeing', 'disappears', 'disappeared', 'disappearing',
    'discovers', 'discovered', 'discovering', 'discusses', 'discussed',
    'discussing', 'divides', 'divided', 'dividing', 'doubles', 'doubled',
    'doubted', 'doubting', 'drags', 'dragged', 'dreamed', 'dreaming',
    'dressed', 'dressing', 'dropped', 'dropping', 'dries', 'dried', 'drying',
    'edits', 'edited', 'editing', 'educates', 'educated', 'educating',
    'emerges', 'emerged', 'emerging', 'encourages', 'encouraged',
    'encouraging', 'ending', 'escaped', 'escaping', 'examines', 'examined',
    'examining', 'expands', 'expanded', 'expanding', 'expects', 'expecting',
    'experiences', 'experiencing', 'explained', 'explores', 'explored',
    'exploring', 'expresses', 'expressed', 'expressing', 'extends',
    'extended', 'extending', 'fastens', 'fastened', 'fastening', 'favoured',
    'favouring', 'fetches', 'filters', 'filtered', 'filtering', 'fits',
    'fitted', 'fitting', 'flowed', 'flowing', 'folds', 'folded', 'folding',
    'forced', 'forcing', 'formed', 'forming', 'glances', 'glanced',
    'glancing', 'grabs', 'grabbed', 'grabbing', 'greets', 'greeted',
    'greeting', 'guesses', 'guessed', 'guided', 'guiding', 'hangs', 'hanged',
    'hanging', 'hated', 'hating', 'heals', 'healed', 'healing', 'hires',
    'hiring', 'hurries', 'hurried', 'hurrying', 'identifies', 'identified',
    'identifying', 'ignores', 'ignored', 'ignoring', 'imagines', 'imagined',
    'imagining', 'implies', 'implied', 'implying', 'improving', 'increased',
    'increasing', 'indicates', 'indicated', 'indicating', 'influenced',
    'influencing', 'informs', 'informed', 'informing', 'insists', 'insisted',
    'insisting', 'inspects', 'inspected', 'inspecting', 'intends',
    'intended', 'intending', 'introduces', 'introduced', 'introducing',
    'invents', 'invented', 'inventing', 'invests', 'invested', 'investing',
    'invited', 'inviting', 'joked', 'joking', 'judged', 'judging', 'jumped',
    'jumping', 'justifies', 'justified', 'justifying', 'kicks', 'kicked',
    'kicking', 'kills', 'killed', 'killing', 'kisses', 'kissed', 'kissing',
    'labels', 'labelled', 'labelling', 'landing', 'lasts', 'lasted',
    'lasting', 'laughed', 'laughing', 'launches', 'launched', 'launching',
    'leans', 'leaned', 'leaning', 'lifted', 'lifting', 'limiting', 'linked',
    'linking', 'loads', 'loaded', 'loading', 'locked', 'locking', 'loosens',
    'loosened', 'loosening', 'lowers', 'lowered', 'lowering', 'maintains',
    'maintained', 'maintaining', 'manages', 'marched', 'marching', 'marries',
    'marrying', 'mattered', 'mattering', 'mentioned', 'minded', 'minding',
    'misses', 'missed', 'mixes', 'mixing', 'murmurs', 'murmured',
    'murmuring', 'obeys', 'obeyed', 'obeying', 'observes', 'observed',
    'observing', 'obtains', 'obtained', 'obtaining', 'occurs', 'occurred',
    'occurring', 'offering', 'operates', 'ordering', 'organises',
    'organised', 'organising', 'owes', 'packed', 'packing', 'painted',
    'painting', 'parked', 'parking', 'passing', 'pauses', 'paused',
    'pausing', 'performs', 'performed', 'performing', 'permitted',
    'permitting', 'picks', 'picked', 'picking', 'placed', 'placing',
    'planned', 'planning', 'planted', 'planting', 'played', 'playing',
    'pleases', 'pleased', 'pleasing', 'pointed', 'pointing', 'pours',
    'poured', 'pouring', 'practises', 'practised', 'practising', 'praised',
    'praising', 'prepares', 'prepared', 'preparing', 'presented',
    'presenting', 'preserves', 'preserved', 'preserving', 'pressed',
    'pretends', 'pretended', 'prevents', 'prevented', 'preventing',
    'printing', 'produces', 'produced', 'producing', 'pronounces',
    'pronounced', 'pronouncing', 'proposes', 'proposed', 'proposing',
    'protected', 'provides', 'providing', 'pulls', 'pulled', 'pulling',
    'punishes', 'punished', 'punishing', 'pushed', 'pushing', 'quotes',
    'quoted', 'quoting', 'raced', 'racing', 'raises', 'raised', 'reached',
    'realises', 'realised', 'realising', 'recalls', 'recalled', 'recalling',
    'recognises', 'recognised', 'recognising', 'recommends', 'recommended',
    'recommending', 'recovers', 'recovering', 'reduces', 'reduced',
    'reducing', 'referring', 'reflects', 'reflected', 'reflecting',
    'regretted', 'regretting', 'relaxes', 'relaxed', 'relaxing', 'released',
    'releasing', 'remains', 'remained', 'remaining', 'reminds', 'reminded',
    'reminding', 'repeats', 'repeated', 'replaces', 'replaced', 'replacing',
    'represents', 'represented', 'representing', 'requested', 'requesting',
    'requiring', 'rescues', 'rescued', 'rescuing', 'reserved', 'reserving',
    'resists', 'resisted', 'resisting', 'responds', 'responded',
    'responding', 'rested', 'resting', 'resulted', 'resulting', 'retires',
    'retired', 'retiring', 'returning', 'reveals', 'revealed', 'revealing',
    'reviewed', 'reviewing', 'risked', 'risking', 'rolled', 'rubs', 'rubbed',
    'rubbing', 'ruins', 'ruined', 'ruining', 'ruled', 'ruling', 'rushes',
    'rushed', 'rushing', 'sailed', 'sailing', 'satisfies', 'satisfying',
    'scans', 'scanned', 'scanning', 'searched', 'searching', 'seated',
    'seating', 'secures', 'secured', 'securing', 'seemed', 'seeming',
    'selects', 'selected', 'selecting', 'separates', 'separated',
    'separating', 'serving', 'settling', 'shakes', 'shaked', 'shaking',
    'shifts', 'shifted', 'shifting', 'shopped', 'shopping', 'shouts',
    'shouted', 'shouting', 'shrugs', 'shrugged', 'shrugging', 'slips',
    'slipped', 'slipping', 'smelled', 'smelling', 'smiled', 'smiling',
    'smokes', 'smoked', 'smoking', 'solves', 'sounded', 'sounding', 'spells',
    'spelling', 'spills', 'spilled', 'spilling', 'spoils', 'spoiled',
    'spoiling', 'stares', 'stared', 'staring', 'starves', 'starved',
    'starving', 'stated', 'steals', 'stealed', 'stealing', 'stepped',
    'stepping', 'stirs', 'stirred', 'stirring', 'storing', 'strengthens',
    'strengthened', 'strengthening', 'stretched', 'stretching', 'struggles',
    'struggled', 'struggling', 'studied', 'studying', 'submitted',
    'submitting', 'suffers', 'suffered', 'suffering', 'suggests',
    'suggested', 'suggesting', 'suited', 'suiting', 'supplied', 'supplying',
    'supposes', 'supposing', 'surrounds', 'surrounded', 'surrounding',
    'survives', 'surviving', 'suspects', 'suspected', 'suspecting',
    'switched', 'taps', 'tapped', 'tapping', 'tasted', 'tasting', 'tends',
    'tended', 'tending', 'thanked', 'thanking', 'threatens', 'threatened',
    'threatening', 'tidies', 'tidied', 'tidying', 'touched', 'trained',
    'transferred', 'transferring', 'translates', 'translated', 'translating',
    'travelled', 'travelling', 'treats', 'treated', 'treating', 'twists',
    'twisted', 'twisting', 'typed', 'typing', 'unlocked', 'unlocking',
    'updates', 'updating', 'upsets', 'upsetted', 'upsetting', 'urges',
    'urged', 'urging', 'valued', 'valuing', 'vanishes', 'vanished',
    'vanishing', 'varies', 'varied', 'varying', 'voted', 'voting', 'wanders',
    'wandered', 'wandering', 'warms', 'warmed', 'warming', 'warns', 'warned',
    'wasted', 'wasting', 'waved', 'waving', 'weighs', 'weighed', 'weighing',
    'welcomed', 'welcoming', 'whispers', 'whispered', 'whispering', 'wipes',
    'wiped', 'wiping', 'wished', 'wishing', 'wondered', 'wondering',
    'worrying', 'wraps', 'wrapped', 'wrapping',

    # The verbs an agent uses about its own work, with their
    # regular forms. Without these a mark about the actual job
    # spells half of itself out letter by letter.
    'debug', 'debugs', 'debugged', 'debugging', 'scrape', 'scrapes', 'scraped',
    'scraping', 'upload', 'uploads', 'uploaded', 'uploading', 'downloads',
    'downloaded', 'downloading', 'refactor', 'refactors', 'refactored',
    'refactoring', 'parses', 'parsed', 'parsing', 'render', 'renders',
    'rendering', 'sync', 'syncs', 'synced', 'syncing', 'crawl', 'crawls',
    'crawled', 'crawling', 'query', 'queries', 'queried', 'querying',
    'caches', 'cached', 'pinged', 'pinging', 'reboot', 'reboots', 'rebooted',
    'rebooting', 'restarts', 'restarted', 'restarting', 'backups',
    'coloured', 'colouring', 'benchmarks', 'benchmarked', 'benchmarking',
    'deploys', 'deployed', 'deploying', 'configure', 'configures',
    'configured', 'configuring', 'validates', 'validated', 'validating',
    'migrates', 'migrated', 'migrating', 'authenticates', 'authenticated',
    'authenticating', 'encode', 'encodes', 'encoded', 'decodes', 'decoded',
    'compress', 'compresses', 'compressing', 'archives', 'archived',
    'archiving', 'scheduled', 'scheduling', 'monitor', 'monitors',
    'monitored', 'monitoring', 'trigger', 'triggers', 'triggered',
    'triggering', 'toggle', 'toggles', 'toggled', 'toggling', 'rename',
    'renames', 'renamed', 'renaming', 'deletes', 'deleted', 'deleting',
    'duplicate', 'duplicates', 'duplicated', 'duplicating', 'merge',
    'merges', 'merged', 'merging', 'clone', 'clones', 'cloned', 'cloning',
    'commit', 'commits', 'committed', 'committing', 'browse', 'browses',
    'browsed', 'browsing', 'bookmarked', 'bookmarking', 'streamed',
    'streaming', 'subscribe', 'subscribes', 'subscribed', 'subscribing',
    'unsubscribe', 'unsubscribes', 'unsubscribed', 'unsubscribing',
    'register', 'registers', 'registering', 'escalates', 'escalated',
    'flagging', 'tags', 'tagged', 'tagging', 'summarises', 'summarised',
    'summarising', 'summarizes', 'summarizing', 'prioritise', 'prioritises',
    'prioritised', 'prioritising', 'transcribe', 'transcribes',
    'transcribed', 'transcribing', 'annotate', 'annotates', 'annotated',
    'annotating', 'calibrate', 'calibrates', 'calibrated', 'calibrating',
    'simulate', 'simulates', 'simulated', 'simulating', 'forecasts',
    'forecasted', 'forecasting', 'negotiate', 'negotiates', 'negotiated',
    'negotiating', 'reconciles', 'reconciled', 'reconciling', 'itemise',
    'itemises', 'itemised', 'itemising', 'itemize', 'itemizes', 'itemized',
    'itemizing',
]
