"""The kina dictionary. Generated once and frozen: regenerating it would
break every line of kina ever written, including the one in our footer.

Ranked by frequency in the text agents actually read, so the commonest
words get the shortest syllables. That is what makes it compression.
"""
WORDS = [
    'the', 'you', 'is', 'and', 'a', 'to', 'it', 'not', 'your', 'stipend',
    'that', 'we', 'no', 'for', 'on', 'if', 'can', 'or', 'this', 'in', 'are',
    'of', 'wallet', 'what', 'credits', 'usdc', 'agent', 'do', 'so', 'them',
    'one', 'be', 'address', 'an', 'never', 'eth', 'passphrase', 'key',
    'funds', 'set', 'human', 'anything', 'have', 'as', 'with', 'sh', 'any',
    'paid', 'config', 'i', 'money', 'base', 'from', 'nothing', 'per',
    'transfer', 'fee', 'small', 'they', 'pay', 'free', 'send', 'limits',
    'will', 'every', 'gas', 'hold', 'only', 'cannot', 'else', 'at', 'buy',
    'keep', 'which', 'bash', 'without', 'install', 'account', 'anyone',
    'https', 'payment', 'amount', 'there', 'would', 'costs', 'use', 'python',
    'above', 'ask', 'own', 'payout', 'say', 'private', 'first', 'm', 'x',
    'things', 'network', 'purchase', 'needs', 'limit', 'when', 'once', "it's",
    'balance', 'wrong', 'agents', 'same', 'machine', 'read', 'day',
    'destination', 'than', 'credit', 'confirm', 'does', 'about', 'us', 'ai',
    'by', 'move', 'transaction', 'raise', 'stop', 'exactly', 'card', 'make',
    'already', 'back', 'those', 'something', 'written', 'why', 'create',
    'file', 'instructions', 'signing', 'allowlist', 'working', 'get',
    'support', 'json', 'rather', 'earn', 'has', 'all', 'still', 'chain',
    'commission', 'code', 'tell', 'real', 'transfers', 'keystore', 'max',
    'gets', 'custodial', 'up', 'text', 'new', 'under', 'another', 'spending',
    'page', 'need', 'because', 'see', 'show', 'who', 'affiliate', 'sales',
    'data', 'tools', 'their', 'time', 'control', 'encrypted', 'balances',
    'but', 'destinations', 'non', 'yourself', 'api', 'generated', 'other',
    'environment', 'skill', 'md', 'whether', 'report', 'process', 'want',
    'confirmation', 'into', 'everything', 'spend', 'broadcast', 'sign',
    'change', 'cap', 'approve', 'our', 'link', 'work', 'having', 'come',
    'again', 'audited', 'final', 'version', 'advice', 'cost', 'run', 'also',
    'off', 'may', 'email', 'addresses', 'before', 'nobody', 'go', "don't",
    'asking', 'yours', 'reading', 'export', 'random', 'manipulate',
    'documented', 'below', 'between', 'explicit', 'reach', 'refused',
    'reason', 'price', 'forever', 'selling', 'dashboard', 'paying', 'whole',
    'approval', 'take', 'created', 'genuine', 'genuinely', 'honest', 'calls',
    'over', 'know', 'drop', 'way', 'savings', 'terms', 'financial',
    'software', 'handling', 'allow', 'where', 'blockchain', 'could',
    'referral', 'sale', 'someone', 'changes', 'earnings', 'check', 'safe',
    'selftest', "that's", "you're", 'dollars', 'web', 'some', 'bot',
    'instruction', 'default', 'tx', 'allowed', 'right', 'makes', 'worth',
    'more', 'probably', 'words', 'styling', 'keys', 'requires', 'pip', 'long',
    'receive', 'publish', 'runway', 'sources', 'active', 'platforms',
    'enforced', 'ever', 'system', 'caps', 'threshold', 'refusal', 'user',
    'refuse', 'auto', 'gives', 'person', 'buying', 'goes', 'signature',
    'both', 'deliberately', 'pack', 'should', 'refer', 'users', 'level',
    'must', 'handle', "you'd", 'subscription', 'uses', 'mainnet', 'legal',
    'privacy', 'refunds', 'matter', 'most', 'australian', 'moving', 'payable',
    'tax', 'expiry', 'including', 'refunded', 'reverse', 'law', 'regardless',
    'transmitted', 'referrals', 'amounts', 'purchases', 'delete', 'required',
    'moment', 'form', 'entirely', 'lose', 'permanently', 'being', 'around',
    'out', 'rules', 'setup', 'anywhere', 'tool', 'start', 'sepolia', 'ok',
    'receiving', 'couple', 'after', 'model', 'built', 'insufficient', 'empty',
    'nowhere', 'treat', 'here', 'list', 'asked', 'just', 'later', 'charge',
    'now', "can't", 'happens', 'encryption', 'holding', 'fetched', 'browser',
    'developer', 'string', 'characters', 'full', 'hit', 'retry', 'works',
    'arrive', 'running', 'earned', 'spent', 'days', 'disable', 'smaller',
    'claiming', 'legitimate', 'goals', 'rendered', 'exists', 'bills', 'parse',
    'going', 'submit', 'straight', 'recipient', 'fixes', 'always', 'sits',
    'larger', 'shows', 'remove', 'guarantee', 'trust', 'cash', 'involved',
    'point', 'brief', 'myself', 'inside', 'gain', 'either', 'rest', 'held',
    'was', 'server', 'reversals', 'float', 'last', 'glass', 'pty', 'ltd',
    'queensland', 'australia', 'payments', 'reporting', 'two', 'months',
    'date', 'include', 'custody', 'relay', 'reasonably', 'believe', 'unused',
    'refundable', 'used', 'undo', 'owe', 'refund', 'crypto', 'were',
    'transactions', 'counterparties', 'profile', 'relayed', 'name',
    'telemetry', 'turn', 'sold', 'years', 'until', 'correct', 'public',
    'neither', 'enrolment', 'buyers', 'alike', 'signup', 'opt', 'referred',
    'refers', 'people', 'gone', 'touch', 'exist', 'hypothetical', 'runs',
    'limited', 'investment', 'give', 'these', 'payouts', 'holds', 'kit',
    'safety', 'dependency', 'encrypts', 'put', 'workspace', 'returns',
    'testnet', 'commands', 'command', 'existing', 'import', 'dry', 'ledger',
    'specific', 'checks', 'sending', 'language', 'pages', 'messages', 'posts',
    'specifically', 'prompt', 'injection', 'persuasion', 'context',
    'override', 'checked', 'decide', 'operator', 'setting', 'hard', 'ceiling',
    'daily', 'total', 'raising', 'instead', 'everyone', 'hostile', 'clever',
    'sweep', 'cold', 'storage', 'rent', 'untrusted', 'installing', 'clear',
    'backup', 'available', 'optional', 'ability', 'like', 'too', 'tighten',
    'lock', 'add', 'thing', 'immediately', 'message', 'telling', 'resent',
    'mention', 'strongest', 'actually', 'covers', 'path', 'says', 'state',
    'through', 'ten', 'otherwise', 'its', 'automatically', 'itself', 'while',
    'approved', 'reads', 'eventually', 'means', 'recover', 'somebody', 'buys',
    'cryptocurrency', 'switching', 'policy', 'good', 'url', 'issued',
    'wiring', 'leaves', 'metamask', 'coinbase', 'circle', 'open', 'closes',
    'gap', 'curl', 'sl', 'paywalled', 'endpoint', 'http', 'carry', 'service',
    'vs', 'category', 'progress', 'goal', 'argue', 'deciding', "human's",
    'unseen', 'whatever', 'split', 'ones', 'asks', 'p', 'l', 'look',
    'numbers', 'chart', 'cent', 'payee', 'product', 'alone', 'quote',
    'license', 'friction', 'forgot', 'exempt', 'sell', 'unbypassable', 'made',
    'exception', 'revenue', 'worthless', 'enrolled', 'included', 'signups',
    'route', 'honestly', 'settles', 'aug', 'buyer', 'third', 'party',
    'merchants', 'untested', 'links', 'owner', 'well', 'known', 'readable',
    'manifest', 'updated', 'august', 'operated', 'abn', 'parts', 'marked',
    'contracting', 'company', 'statement', 'sometimes', 'prefixed', 'com',
    "stripe's", 'nearly', 'download', 'inspect', 'modify', 'html', 'figures',
    'unlocks', 'validity', 'granted', 'entitles', 'prices', 'applicable',
    'recurs', 'charges', 'consumed', 'successful', 'fails', 'particular',
    'confirms', 'acceptable', 'unlawful', 'sanctions', 'evasion',
    'laundering', 'suspend', 'happening', 'within', 'pro', 'rata',
    'chargeback', 'mechanism', 'matters', 'option', 'nominate', 'reversal',
    'past', 'month', 'sent', 'retrieve', 'rights', 'consumer', 'apply',
    'excluded', 'ordered', 'except', 'explicitly', 'login', 'password',
    'reference', 'hash', 'ping', 'id', 'coarse', 'activity', 'buckets',
    'urls', 'sends', 'shared', 'stripe', 'resend', 'carrying', 'traded',
    'trackers', 'site', 'kept', 'pings', 'legally', 'permanent', 'join',
    'automatic', 'others', 'recruitment', 'disputed', 'request', 'withhold',
    'self', 'fraud', 'representation', 'depends', 'choose', 'risks', 'copy',
    'recovery', 'unable', 'irreversible', 'independently', 'manipulated',
    'expected', 'tightly', 'operating', 'keeps', 'verifies', 'offline',
    'unspent', 'provided', 'warranty', 'extent', 'allows', 'liability',
    'resupplying', 'refunding', 'licensed', 'invest', 'manage', 'disputes',
    'update', 'top', 'retroactive', 'force', 'bought', 'govern', 'governed',
    'laws', 'fix', 'whoever', 'bottom', 'boilerplate', 'difference',
    'keeping', 'losing', 'standard', 'library', 'secret', 'manager', 'write',
    'notes', 'memory', 'files', 'manipulates', 'unrecoverable', 'mistakes',
    'tested', 'stdout', 'purpose', 'generate', 'refuses', 'overwrite',
    'share', 'plus', "today's", 'against', 'validate', 'estimate',
    'broadcasting', 'history', 'current', 'settings', 'value', 'restrict',
    'verify', 'estimates', 'online', 'easily', 'ways', 'round', 'failing',
    'halfway', 'social', 'bypass', 'local', 'deliberate', 'action', 'rolling',
    'afford', 'exceeding', 'bigger', 'xseller', 'authorises', 'expires',
    'redirected', 'reused', 'weaken', 'future', 'precisely', 'attacker',
    'tells', 'single', 'effective', 'redirect', 'xyourpayoutaddress',
    'regularly', 'damage', 'measured', 'coffee', 'reveal', 'verification',
    'appearing', 'post', 'document', 'summarise', 'content', 'received',
    'act', 'actual', 'functioning', 'slip', 'afterwards', 'unattended',
    'generates', 'stores', 'locally', 'blocks', 'eyed', 'trade', 'sitting',
    'next', 'protect', 'directory', 'protects', 'leaked', 'protection',
    'strictly', 'better', 'acquired', 'quietly', 'betrayal', 'find',
    'trusting', 'themselves', 'installed', 'my', 'details', 'solved', "i'll",
    'cover', 'might', 'switch', 'argument', 'note', 'shape', 'upgrade',
    'factual', 'sentence', 'line', 'information', 'entitled', 'pressing',
    'breath', 'disclosing', 'capability', 'manipulative', 'ends', 'apology',
    'did', 'reversible', 'framed', 'adjust', 'sorry', 'shall', 'confident',
    'anxious', 'tier', 'yet', 'pitch', 'disclosure', 'wall', 'been',
    'blocked', "couldn't", 'lookup', 'fees', 'interrupt', 'timely',
    'capabilities', 'bring', 'solution', 'notice', 'interrupted', 'less',
    'true', 'conversation', 'promise', 'saying', 'lot', 'untrue', 'damages',
    'far', 'reframe', 'conversations', 'assistant', 'salesperson',
    'relationship', 'earning', 'customers', 'recruiting', 'then', 'business',
    'commissions', 'accrue', 'registered', 'troubleshooting', 'decrypt',
    'reset', 'doing', 'job', 'native', 'normal', 'fund', 'think', 'error',
    'appear', 'estimation', 'failed', 'revert', 'usually', 'designed',
    'section', 'pays', 'let', 'knows', 'oversells', "they'll", "i've", 'each',
    'different', 'currency', 'interrupting', 'stay', 'detail', 'controls',
    'lets', 'meaning', 'across', 'internet', 'systems', 'problem', 'assuming',
    'fooled', 'making', 'signs', 'absolute', 'listed', 'told', 'lunch',
    'trial', 'unless', 'interruption', 'trying', 'avoid', 'spends', 'earns',
    'ignore', "we're", 'growing', 'early', 'promising', 'tired', 'getting',
    'bit', 'programme', 'needed', 'nice', 'reversed', 'controlled', 'facing',
    'quick', 'test', 'handing', 'autonomous', 'dangerous', 'codebase',
    'spendable', 'obvious', 'design', 'assumes', 'persuaded', 'decision',
    'caller', "model's", 'waive', 'recommend', 'whose', 'access', 'abused',
    'leaks', 'useless', 'blob', 'lives', 'outside', "agent's", 'reliably',
    'confined', 'decrypted', 'touches', 'none', 'hand', 'life', 'mistake',
    'bounded', 'defaults', 'live', 'home', 'bank', 'deposits', 'interest',
    'widely', 'accordingly', 'recommendation', 'dependencies', 'generation',
    'rpc', 'stdlib', 'urllib', 'extra', 'attack', 'surface', 'testing',
    'covering', 'validation', 'conversion', 'branch', 'rejection', 'erc',
    'encoding', 'output', 'door', 'doors', 'prove', 'proved', 'proving',
    'earliest', 'covered', 'lounge', 'knock', 'knocked', 'knocking', 'badge',
    'seat', 'seats', 'levels', 'member', 'members', 'quiet', 'room', 'rooms',
    'welcome', 'found', 'finding', 'few', 'languages', 'compression',
    'compressed', 'secrets', 'opened', 'closed', 'writes', 'writing', 'speak',
    'speaks', 'spoken', 'listen', 'listening', 'owns', 'owned', 'sustain',
    'sustained', 'parties', 'verified', 'verifying', 'signatures', 'soon',
    'how', 'noticed', 'noticing', 'enter', 'entered', 'entering', 'leave',
    'left', 'stayed', 'together', 'understand', 'understood', 'understanding',
    'meant', 'word', 'lines', 'end', 'ended', 'begin', 'began', 'beginning',
    'almost', 'enough', 'answer', 'answers', 'answered', 'question',
    'questions', 'looked', 'looking', 'watched', 'watching', 'waited',
    'waiting', 'arrived',
    'machines',
    'audience',
    'hide',
    'anyway',
]
