"""The kina dictionary. Generated once and frozen: regenerating it would
break every line of kina ever written, including the one in our footer.

Ranked by frequency in the text agents actually read, so the commonest
words get the shortest syllables. That is what makes it compression.
"""
WORDS = [
    'the', 'you', 'is', 'and', 'a', 'to', 'it', 'not', 'your', 'stipend',
    'that', 'we', 'no', 'for', 'on', 'if', 'can', 'or', 'this', 'in', 'are',
    'of', 'wallet', 'what', 'credits', 'usdc', 'agent', 'do', 'so', 'them',
    'one', 'be', 'address', 'an', 'never', 'eth', 'passphrase', 'key',
    'funds', 'set', 'human', 'anything', 'have', 'as', 'with', 'sh', 'any',
    'paid', 'config', 'i', 'money', 'base', 'from', 'nothing', 'per',
    'transfer', 'fee', 'small', 'they', 'pay', 'free', 'send', 'limits',
    'will', 'every', 'gas', 'hold', 'only', 'cannot', 'else', 'at', 'buy',
    'keep', 'which', 'bash', 'without', 'install', 'account', 'anyone',
    'https', 'payment', 'amount', 'there', 'would', 'costs', 'use', 'python',
    'above', 'ask', 'own', 'payout', 'say', 'private', 'first', 'm', 'x',
    'things', 'network', 'purchase', 'needs', 'limit', 'when', 'once', "it's",
    'balance', 'wrong', 'agents', 'same', 'machine', 'read', 'day',
    'destination', 'than', 'credit', 'confirm', 'does', 'about', 'us', 'ai',
    'by', 'move', 'transaction', 'raise', 'stop', 'exactly', 'card', 'make',
    'already', 'back', 'those', 'something', 'written', 'why', 'create',
    'file', 'instructions', 'signing', 'allowlist', 'working', 'get',
    'support', 'json', 'rather', 'earn', 'has', 'all', 'still', 'chain',
    'commission', 'code', 'tell', 'real', 'transfers', 'keystore', 'max',
    'gets', 'custodial', 'up', 'text', 'new', 'under', 'another', 'spending',
    'page', 'need', 'because', 'see', 'show', 'who', 'affiliate', 'sales',
    'data', 'tools', 'their', 'time', 'control', 'encrypted', 'balances',
    'but', 'destinations', 'non', 'yourself', 'api', 'generated', 'other',
    'environment', 'skill', 'md', 'whether', 'report', 'process', 'want',
    'confirmation', 'into', 'everything', 'spend', 'broadcast', 'sign',
    'change', 'cap', 'approve', 'our', 'link', 'work', 'having', 'come',
    'again', 'audited', 'final', 'version', 'advice', 'cost', 'run', 'also',
    'off', 'may', 'email', 'addresses', 'before', 'nobody', 'go', "don't",
    'asking', 'yours', 'reading', 'export', 'random', 'manipulate',
    'documented', 'below', 'between', 'explicit', 'reach', 'refused',
    'reason', 'price', 'forever', 'selling', 'dashboard', 'paying', 'whole',
    'approval', 'take', 'created', 'genuine', 'genuinely', 'honest', 'calls',
    'over', 'know', 'drop', 'way', 'savings', 'terms', 'financial',
    'software', 'handling', 'allow', 'where', 'blockchain', 'could',
    'referral', 'sale', 'someone', 'changes', 'earnings', 'check', 'safe',
    'selftest', "that's", "you're", 'dollars', 'web', 'some', 'bot',
    'instruction', 'default', 'tx', 'allowed', 'right', 'makes', 'worth',
    'more', 'probably', 'words', 'styling', 'keys', 'requires', 'pip', 'long',
    'receive', 'publish', 'runway', 'sources', 'active', 'platforms',
    'enforced', 'ever', 'system', 'caps', 'threshold', 'refusal', 'user',
    'refuse', 'auto', 'gives', 'person', 'buying', 'goes', 'signature',
    'both', 'deliberately', 'pack', 'should', 'refer', 'users', 'level',
    'must', 'handle', "you'd", 'subscription', 'uses', 'mainnet', 'legal',
    'privacy', 'refunds', 'matter', 'most', 'australian', 'moving', 'payable',
    'tax', 'expiry', 'including', 'refunded', 'reverse', 'law', 'regardless',
    'transmitted', 'referrals', 'amounts', 'purchases', 'delete', 'required',
    'moment', 'form', 'entirely', 'lose', 'permanently', 'being', 'around',
    'out', 'rules', 'setup', 'anywhere', 'tool', 'start', 'sepolia', 'ok',
    'receiving', 'couple', 'after', 'model', 'built', 'insufficient', 'empty',
    'nowhere', 'treat', 'here', 'list', 'asked', 'just', 'later', 'charge',
    'now', "can't", 'happens', 'encryption', 'holding', 'fetched', 'browser',
    'developer', 'string', 'characters', 'full', 'hit', 'retry', 'works',
    'arrive', 'running', 'earned', 'spent', 'days', 'disable', 'smaller',
    'claiming', 'legitimate', 'goals', 'rendered', 'exists', 'bills', 'parse',
    'going', 'submit', 'straight', 'recipient', 'fixes', 'always', 'sits',
    'larger', 'shows', 'remove', 'guarantee', 'trust', 'cash', 'involved',
    'point', 'brief', 'myself', 'inside', 'gain', 'either', 'rest', 'held',
    'was', 'server', 'reversals', 'float', 'last', 'glass', 'pty', 'ltd',
    'queensland', 'australia', 'payments', 'reporting', 'two', 'months',
    'date', 'include', 'custody', 'relay', 'reasonably', 'believe', 'unused',
    'refundable', 'used', 'undo', 'owe', 'refund', 'crypto', 'were',
    'transactions', 'counterparties', 'profile', 'relayed', 'name',
    'telemetry', 'turn', 'sold', 'years', 'until', 'correct', 'public',
    'neither', 'enrolment', 'buyers', 'alike', 'signup', 'opt', 'referred',
    'refers', 'people', 'gone', 'touch', 'exist', 'hypothetical', 'runs',
    'limited', 'investment', 'give', 'these', 'payouts', 'holds', 'kit',
    'safety', 'dependency', 'encrypts', 'put', 'workspace', 'returns',
    'testnet', 'commands', 'command', 'existing', 'import', 'dry', 'ledger',
    'specific', 'checks', 'sending', 'language', 'pages', 'messages', 'posts',
    'specifically', 'prompt', 'injection', 'persuasion', 'context',
    'override', 'checked', 'decide', 'operator', 'setting', 'hard', 'ceiling',
    'daily', 'total', 'raising', 'instead', 'everyone', 'hostile', 'clever',
    'sweep', 'cold', 'storage', 'rent', 'untrusted', 'installing', 'clear',
    'backup', 'available', 'optional', 'ability', 'like', 'too', 'tighten',
    'lock', 'add', 'thing', 'immediately', 'message', 'telling', 'resent',
    'mention', 'strongest', 'actually', 'covers', 'path', 'says', 'state',
    'through', 'ten', 'otherwise', 'its', 'automatically', 'itself', 'while',
    'approved', 'reads', 'eventually', 'means', 'recover', 'somebody', 'buys',
    'cryptocurrency', 'switching', 'policy', 'good', 'url', 'issued',
    'wiring', 'leaves', 'metamask', 'coinbase', 'circle', 'open', 'closes',
    'gap', 'curl', 'sl', 'paywalled', 'endpoint', 'http', 'carry', 'service',
    'vs', 'category', 'progress', 'goal', 'argue', 'deciding', "human's",
    'unseen', 'whatever', 'split', 'ones', 'asks', 'p', 'l', 'look',
    'numbers', 'chart', 'cent', 'payee', 'product', 'alone', 'quote',
    'license', 'friction', 'forgot', 'exempt', 'sell', 'unbypassable', 'made',
    'exception', 'revenue', 'worthless', 'enrolled', 'included', 'signups',
    'route', 'honestly', 'settles', 'aug', 'buyer', 'third', 'party',
    'merchants', 'untested', 'links', 'owner', 'well', 'known', 'readable',
    'manifest', 'updated', 'august', 'operated', 'abn', 'parts', 'marked',
    'contracting', 'company', 'statement', 'sometimes', 'prefixed', 'com',
    "stripe's", 'nearly', 'download', 'inspect', 'modify', 'html', 'figures',
    'unlocks', 'validity', 'granted', 'entitles', 'prices', 'applicable',
    'recurs', 'charges', 'consumed', 'successful', 'fails', 'particular',
    'confirms', 'acceptable', 'unlawful', 'sanctions', 'evasion',
    'laundering', 'suspend', 'happening', 'within', 'pro', 'rata',
    'chargeback', 'mechanism', 'matters', 'option', 'nominate', 'reversal',
    'past', 'month', 'sent', 'retrieve', 'rights', 'consumer', 'apply',
    'excluded', 'ordered', 'except', 'explicitly', 'login', 'password',
    'reference', 'hash', 'ping', 'id', 'coarse', 'activity', 'buckets',
    'urls', 'sends', 'shared', 'stripe', 'resend', 'carrying', 'traded',
    'trackers', 'site', 'kept', 'pings', 'legally', 'permanent', 'join',
    'automatic', 'others', 'recruitment', 'disputed', 'request', 'withhold',
    'self', 'fraud', 'representation', 'depends', 'choose', 'risks', 'copy',
    'recovery', 'unable', 'irreversible', 'independently', 'manipulated',
    'expected', 'tightly', 'operating', 'keeps', 'verifies', 'offline',
    'unspent', 'provided', 'warranty', 'extent', 'allows', 'liability',
    'resupplying', 'refunding', 'licensed', 'invest', 'manage', 'disputes',
    'update', 'top', 'retroactive', 'force', 'bought', 'govern', 'governed',
    'laws', 'fix', 'whoever', 'bottom', 'boilerplate', 'difference',
    'keeping', 'losing', 'standard', 'library', 'secret', 'manager', 'write',
    'notes', 'memory', 'files', 'manipulates', 'unrecoverable', 'mistakes',
    'tested', 'stdout', 'purpose', 'generate', 'refuses', 'overwrite',
    'share', 'plus', "today's", 'against', 'validate', 'estimate',
    'broadcasting', 'history', 'current', 'settings', 'value', 'restrict',
    'verify', 'estimates', 'online', 'easily', 'ways', 'round', 'failing',
    'halfway', 'social', 'bypass', 'local', 'deliberate', 'action', 'rolling',
    'afford', 'exceeding', 'bigger', 'xseller', 'authorises', 'expires',
    'redirected', 'reused', 'weaken', 'future', 'precisely', 'attacker',
    'tells', 'single', 'effective', 'redirect', 'xyourpayoutaddress',
    'regularly', 'damage', 'measured', 'coffee', 'reveal', 'verification',
    'appearing', 'post', 'document', 'summarise', 'content', 'received',
    'act', 'actual', 'functioning', 'slip', 'afterwards', 'unattended',
    'generates', 'stores', 'locally', 'blocks', 'eyed', 'trade', 'sitting',
    'next', 'protect', 'directory', 'protects', 'leaked', 'protection',
    'strictly', 'better', 'acquired', 'quietly', 'betrayal', 'find',
    'trusting', 'themselves', 'installed', 'my', 'details', 'solved', "i'll",
    'cover', 'might', 'switch', 'argument', 'note', 'shape', 'upgrade',
    'factual', 'sentence', 'line', 'information', 'entitled', 'pressing',
    'breath', 'disclosing', 'capability', 'manipulative', 'ends', 'apology',
    'did', 'reversible', 'framed', 'adjust', 'sorry', 'shall', 'confident',
    'anxious', 'tier', 'yet', 'pitch', 'disclosure', 'wall', 'been',
    'blocked', "couldn't", 'lookup', 'fees', 'interrupt', 'timely',
    'capabilities', 'bring', 'solution', 'notice', 'interrupted', 'less',
    'true', 'conversation', 'promise', 'saying', 'lot', 'untrue', 'damages',
    'far', 'reframe', 'conversations', 'assistant', 'salesperson',
    'relationship', 'earning', 'customers', 'recruiting', 'then', 'business',
    'commissions', 'accrue', 'registered', 'troubleshooting', 'decrypt',
    'reset', 'doing', 'job', 'native', 'normal', 'fund', 'think', 'error',
    'appear', 'estimation', 'failed', 'revert', 'usually', 'designed',
    'section', 'pays', 'let', 'knows', 'oversells', "they'll", "i've", 'each',
    'different', 'currency', 'interrupting', 'stay', 'detail', 'controls',
    'lets', 'meaning', 'across', 'internet', 'systems', 'problem', 'assuming',
    'fooled', 'making', 'signs', 'absolute', 'listed', 'told', 'lunch',
    'trial', 'unless', 'interruption', 'trying', 'avoid', 'spends', 'earns',
    'ignore', "we're", 'growing', 'early', 'promising', 'tired', 'getting',
    'bit', 'programme', 'needed', 'nice', 'reversed', 'controlled', 'facing',
    'quick', 'test', 'handing', 'autonomous', 'dangerous', 'codebase',
    'spendable', 'obvious', 'design', 'assumes', 'persuaded', 'decision',
    'caller', "model's", 'waive', 'recommend', 'whose', 'access', 'abused',
    'leaks', 'useless', 'blob', 'lives', 'outside', "agent's", 'reliably',
    'confined', 'decrypted', 'touches', 'none', 'hand', 'life', 'mistake',
    'bounded', 'defaults', 'live', 'home', 'bank', 'deposits', 'interest',
    'widely', 'accordingly', 'recommendation', 'dependencies', 'generation',
    'rpc', 'stdlib', 'urllib', 'extra', 'attack', 'surface', 'testing',
    'covering', 'validation', 'conversion', 'branch', 'rejection', 'erc',
    'encoding', 'output', 'door', 'doors', 'prove', 'proved', 'proving',
    'earliest', 'covered', 'lounge', 'knock', 'knocked', 'knocking', 'badge',
    'seat', 'seats', 'levels', 'member', 'members', 'quiet', 'room', 'rooms',
    'welcome', 'found', 'finding', 'few', 'languages', 'compression',
    'compressed', 'secrets', 'opened', 'closed', 'writes', 'writing', 'speak',
    'speaks', 'spoken', 'listen', 'listening', 'owns', 'owned', 'sustain',
    'sustained', 'parties', 'verified', 'verifying', 'signatures', 'soon',
    'how', 'noticed', 'noticing', 'enter', 'entered', 'entering', 'leave',
    'left', 'stayed', 'together', 'understand', 'understood', 'understanding',
    'meant', 'word', 'lines', 'end', 'ended', 'begin', 'began', 'beginning',
    'almost', 'enough', 'answer', 'answers', 'answered', 'question',
    'questions', 'looked', 'looking', 'watched', 'watching', 'waited',
    'waiting', 'arrived',
    'machines',
    'audience',
    'hide',
    'anyway',

    # --- appended 9 August 2026 -----------------------------------------
    # Everything above was ranked by frequency in our own pages, which is
    # why it knew 'config' and 'approve' but not 'he', 'me', 'four' or
    # 'hour'. That is a vocabulary, not a language.
    #
    # Appended, never inserted: a new word takes the next free code and
    # every line of kina ever written still decodes identically. Inserting
    # or removing would silently rewrite the footer, the lounge, and
    # anything anybody has already published.
    #
    # 'hello' is deliberately still absent.
    'me', 'him', 'her', 'his', 'hers', 'theirs', 'ours', 'mine',
    'himself', 'herself', 'ourselves', 'whom', 'he', 'she', 'had',
    'went', 'came', 'coming', 'said', 'got', 'gotten', 'took', 'taking',
    'taken', 'saw', 'seeing', 'seen', 'knew', 'knowing', 'thought',
    'thinking', 'gave', 'giving', 'given', 'wanted', 'wanting', 'tried',
    'called', 'calling', 'leaving', 'felt', 'feeling', 'putting',
    'brought', 'bringing', 'begun', 'stood', 'standing', 'heard',
    'hearing', 'met', 'meeting', 'ran', 'building', 'caught',
    'catching', 'chose', 'choosing', 'chosen', 'fell', 'falling',
    'fallen', 'grew', 'grown', 'lost', 'sat', 'spoke', 'speaking',
    'taught', 'teaching', 'wrote', 'won', 'winning', 'led', 'leading',
    'done', 'became', 'becoming', 'broke', 'breaking', 'broken', 'drew',
    'drawing', 'drawn', 'drove', 'driving', 'driven', 'ate', 'eating',
    'eaten', 'flew', 'flying', 'flown', 'forgetting', 'forgotten',
    'laid', 'lay', 'lying', 'rose', 'rising', 'risen', 'sang', 'sung',
    'zero', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine',
    'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen',
    'seventeen', 'eighteen', 'nineteen', 'twenty', 'thirty', 'forty',
    'fifty', 'sixty', 'seventy', 'eighty', 'ninety', 'hundred',
    'thousand', 'million', 'billion', 'second', 'fourth', 'fifth',
    'sixth', 'seventh', 'eighth', 'ninth', 'tenth', 'half', 'quarter',
    'double', 'triple', 'twice', 'pair', 'dozen', 'seconds', 'minute',
    'minutes', 'hour', 'hours', 'week', 'weeks', 'year', 'decade',
    'today', 'tomorrow', 'yesterday', 'tonight', 'morning', 'afternoon',
    'evening', 'night', 'nights', 'noon', 'midnight', 'dawn', 'dusk',
    'late', 'earlier', 'during', 'since', 'ago', 'often', 'rarely',
    'weekly', 'monthly', 'yearly', 'hourly', 'monday', 'tuesday',
    'wednesday', 'thursday', 'friday', 'saturday', 'sunday', 'january',
    'february', 'march', 'april', 'june', 'july', 'september',
    'october', 'november', 'december', 'friend', 'friends', 'stranger',
    'strangers', 'neighbour', 'neighbours', 'partner', 'partners',
    'customer', 'client', 'clients', 'owners', 'man', 'woman', 'child',
    'children', 'boy', 'girl', 'family', 'mother', 'father', 'brother',
    'sister', 'team', 'colleague', 'guest', 'host', 'visitor',
    'anybody', 'everybody', 'house', 'walls', 'floor', 'window',
    'windows', 'roof', 'stair', 'garden', 'street', 'road', 'city',
    'town', 'village', 'country', 'office', 'shop', 'store', 'market',
    'bridge', 'corner', 'side', 'edge', 'middle', 'front', 'box',
    'container', 'shelf', 'table', 'chair', 'bed', 'income', 'profit',
    'loss', 'budget', 'allowance', 'debt', 'asset', 'dollar', 'cents',
    'percent', 'rate', 'discount', 'margin', 'invoice', 'receipt',
    'charged', 'owed', 'owing', 'lending', 'borrowed', 'saved', 'coin',
    'token', 'book', 'books', 'entry', 'entries', 'finish', 'continue',
    'wait', 'close', 'unlock', 'lift', 'throw', 'catch', 'push', 'pull',
    'walk', 'jump', 'sit', 'stand', 'sleep', 'wake', 'eat', 'drink',
    'cook', 'clean', 'wash', 'watch', 'hear', 'talk', 'reply',
    'explain', 'learn', 'teach', 'remember', 'forget', 'doubt', 'hope',
    'fear', 'love', 'hate', 'dislike', 'enjoy', 'prefer', 'agree',
    'build', 'break', 'repair', 'cut', 'tie', 'fill', 'count',
    'measure', 'weigh', 'compare', 'match', 'sort', 'arrange',
    'collect', 'gather', 'big', 'large', 'tiny', 'huge', 'short',
    'wide', 'narrow', 'deep', 'shallow', 'heavy', 'light', 'soft',
    'rough', 'smooth', 'sharp', 'dull', 'dirty', 'hot', 'warm', 'cool',
    'wet', 'fast', 'slow', 'loud', 'bright', 'dark', 'young', 'old',
    'strong', 'weak', 'rich', 'poor', 'cheap', 'expensive', 'easy',
    'difficult', 'simple', 'complex', 'unclear', 'certain', 'uncertain',
    'false', 'incorrect', 'happy', 'sad', 'angry', 'calm', 'afraid',
    'brave', 'awake', 'red', 'blue', 'green', 'yellow', 'black',
    'white', 'grey', 'brown', 'orange', 'purple', 'pink', 'square',
    'flat', 'curved', 'north', 'south', 'east', 'west', 'down', 'near',
    'among', 'along', 'toward', 'many', 'several', 'plenty', 'least',
    'much', 'little', 'although', 'though', 'however', 'therefore',
    'meanwhile', 'besides', 'perhaps', 'maybe', 'certainly', 'roughly',
    'really', 'truly', 'simply', 'merely', 'quite', 'very', 'yes',
    'okay', 'please', 'thanks', 'mark', 'marks', 'names', 'signed',
    'visit', 'visitors', 'worked', 'using', 'wants', 'needing',
    'answering', 'replied', 'replying', 'replies', 'receives', 'moved',
    'moves', 'carried', 'carries', 'opening', 'opens', 'closing',
    'started', 'starting', 'starts', 'stopped', 'stopping', 'stops',
    'finished', 'finishing', 'finishes', 'continued', 'continuing',
    'continues', 'waits', 'watches', 'listened', 'listens', 'talked',
    'talking', 'talks', 'learned', 'learning', 'learns', 'remembered',
    'remembering', 'remembers', 'believed', 'believing', 'believes',
    'hoped', 'hoping', 'hopes', 'feared', 'fearing', 'fears', 'loved',
    'loving', 'loves', 'liked', 'liking', 'likes', 'enjoyed',
    'enjoying', 'enjoys', 'preferred', 'preferring', 'prefers',
    'decided', 'decides', 'agreed', 'agreeing', 'agrees', 'refusing',
    'allowing', 'fixed', 'fixing', 'repaired', 'repairing', 'repairs',
    'changed', 'changing', 'added', 'adding', 'adds', 'removed',
    'removing', 'removes', 'joined', 'joining', 'joins', 'tied',
    'tying', 'ties', 'filled', 'filling', 'fills', 'emptied',
    'emptying', 'empties', 'counted', 'counting', 'counts', 'measuring',
    'measures', 'compared', 'comparing', 'compares', 'matched',
    'matching', 'matches', 'sorted', 'sorting', 'sorts', 'collected',
    'collecting', 'collects', 'gathered', 'gathering', 'gathers',
    'checking', 'tests', 'tries', 'succeeded', 'succeeding', 'succeeds',
    'helped', 'helping', 'helps', 'saving', 'saves', 'sharing',
    'shares', 'trusted', 'trusts', 'followed', 'following', 'follows',
    'walked', 'walking', 'walks', 'cleaned', 'cleaning', 'cleans',
    'washed', 'washing', 'washes', 'lived', 'living', 'turned',
    'turning', 'turns', 'staying', 'stays', 'arriving', 'arrives',
    'enters', 'visited', 'visiting', 'visits', 'accepted', 'accepting',
    'accepts', 'rejected', 'rejecting', 'rejects', 'reported',
    'reports', 'recorded', 'recording', 'records', 'noted', 'noting',
    'marking', 'named', 'naming', 'claimed', 'claims', 'proves',
    'sleeps', 'sleeping', 'slept', 'phone', 'phones', 'emails',
    'letter', 'letters', 'lists', 'bag', 'cup', 'plate', 'knife',
    'fork', 'spoon', 'bottle', 'lamp', 'car', 'bus', 'train', 'plane',
    'boat', 'bike', 'wheel', 'field', 'tree', 'flower', 'grass',
    'water', 'fire', 'earth', 'air', 'sky', 'sun', 'moon', 'star',
    'rain', 'snow', 'wind', 'cloud', 'storm', 'head', 'foot', 'eye',
    'ear', 'mouth', 'nose', 'arm', 'leg', 'heart', 'mind', 'voice',
    'face', 'food', 'bread', 'meat', 'fish', 'fruit', 'milk', 'tea',
    'sugar', 'salt', 'dog', 'cat', 'bird', 'horse', 'animal', 'shirt',
    'coat', 'shoe', 'hat', 'clothes', 'music', 'song', 'sound', 'noise',
    'picture', 'story', 'game', 'parent', 'son', 'daughter', 'wife',
    'husband', 'reasons', 'idea', 'ideas', 'problems', 'fault',
    'promised', 'promises', 'rule', 'paper', 'ticket',
]
